// Данные каталога товаров. Типы — в catalog-types.ts
// Цены — средний рынок б/у РФ для состояния good, в рублях.

import type { CatalogItem } from './catalog-types'

export const CATALOG: CatalogItem[] = [
  // ---------------- Телефоны ----------------
  {
    key: 'iphone-12',
    title: 'iPhone 12 64GB',
    category: 'phones',
    basePrice: 28000,
    jitter: 0.2,
    weight: 2.5,
    desc: [
      'Аккум 85%, всё работает как надо',
      'В чехле и со стеклом с первого дня',
      'Коробка и кабель в комплекте, чек есть',
    ],
  },
  {
    key: 'iphone-11',
    title: 'iPhone 11 64GB',
    category: 'phones',
    basePrice: 19000,
    jitter: 0.2,
    weight: 2.2,
    desc: ['Аккум 82%, держит до вечера', 'Мелкие царапки на рамке, экран цел', 'Продаю из-за апгрейда'],
  },
  {
    key: 'iphone-13',
    title: 'iPhone 13 128GB',
    category: 'phones',
    basePrice: 40000,
    jitter: 0.18,
    weight: 2,
    desc: ['Состояние почти нового, аккум 91%', 'Куплен в официальном магазине', 'Комплект полный, чек сохранён'],
  },
  {
    key: 'iphone-xr',
    title: 'iPhone XR 64GB',
    category: 'phones',
    basePrice: 11500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Батарея живая, держит день', 'Скол на углу корпуса, экран без битых пикселей', 'Только телефон, без коробки'],
  },
  {
    key: 'iphone-se-2020',
    title: 'iPhone SE 2020 64GB',
    category: 'phones',
    basePrice: 9500,
    jitter: 0.25,
    desc: ['Компактный, как из коробки', 'Аккум 88%, Touch ID работает чётко', 'Идеален как второй телефон'],
  },
  {
    key: 'galaxy-s22',
    title: 'Samsung Galaxy S22 128GB',
    category: 'phones',
    basePrice: 35000,
    jitter: 0.2,
    weight: 2,
    desc: ['Амолед яркий, выгораний нет', 'Прошивка официальная, ничего не перепрошивал', 'Пара потёртостей на рамке, экран идеален'],
  },
  {
    key: 'galaxy-s21',
    title: 'Samsung Galaxy S21 128GB',
    category: 'phones',
    basePrice: 23000,
    jitter: 0.22,
    weight: 1.8,
    desc: ['Плёнка с первого дня, экран без царапин', 'Аккум 83%', 'Ухоженный, без вмятин и сколов'],
  },
  {
    key: 'galaxy-a54',
    title: 'Samsung Galaxy A54',
    category: 'phones',
    basePrice: 16000,
    jitter: 0.18,
    weight: 2.2,
    desc: ['Полгода пользовался, как новый', 'Батарея огромная, хватает на два дня', 'Чек и коробка на месте'],
  },
  {
    key: 'redmi-note-12',
    title: 'Xiaomi Redmi Note 12 128GB',
    category: 'phones',
    basePrice: 8500,
    jitter: 0.22,
    weight: 2.5,
    desc: ['Родной чехол в комплекте', 'Всё работает без нареканий', 'Продаю, потому что взял себе флагман'],
  },
  {
    key: 'poco-x5-pro',
    title: 'Poco X5 Pro 256GB',
    category: 'phones',
    basePrice: 11500,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Игровой проц, всё тянёт', 'Царапина на крышке, экран идеален', 'Зарядка быстрая, шнур в комплекте'],
  },
  {
    key: 'realme-gt-neo-3',
    title: 'Realme GT Neo 3',
    category: 'phones',
    basePrice: 12500,
    jitter: 0.25,
    desc: ['Заряжается с нуля за сорок минут', 'Кнопки не люфтят, состояние хорошее', 'Без коробки, только шнур'],
  },
  {
    key: 'pixel-6a',
    title: 'Google Pixel 6a',
    category: 'phones',
    basePrice: 14000,
    jitter: 0.3,
    weight: 0.5,
    desc: ['Привезён из Германии, ловит наши сети отлично', 'Чистый андроид, обновления приходят', 'Камера топовая, состояние отличное'],
  },
  {
    key: 'huawei-p30-pro',
    title: 'Huawei P30 Pro',
    category: 'phones',
    basePrice: 10000,
    jitter: 0.28,
    weight: 0.7,
    desc: ['Зум как у подзорной трубы', 'Без сервисов гугла, всё настроено и работает', 'Корпус в идеале, стекло наклеено'],
  },

  // ---------------- Ноутбуки ----------------
  {
    key: 'macbook-air-2020',
    title: 'MacBook Air 2020 (M1)',
    category: 'laptops',
    basePrice: 55000,
    jitter: 0.15,
    weight: 2,
    desc: [
      'Циклов заряда 210, аккум отличный',
      'Корпус без вмятин, клавиатура целая',
      'Коробка и зарядка в комплекте',
      'Отдаю дешевле рынка, деньги нужны',
    ],
  },
  {
    key: 'macbook-pro-2015',
    title: 'MacBook Pro 13" 2015',
    category: 'laptops',
    basePrice: 24000,
    jitter: 0.25,
    weight: 0.6,
    desc: ['Легенда, работает как часы', 'Аккум менял в прошлом году', 'Потёртости по корпусу, всё работает'],
  },
  {
    key: 'thinkpad-t480',
    title: 'ThinkPad T480 (i5, 16GB)',
    category: 'laptops',
    basePrice: 18000,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Служебный, ухоженный, клавиатура целая', 'Апгрейдится на раз: два слота памяти', 'Батарея держит четыре часа'],
  },
  {
    key: 'thinkpad-x1',
    title: 'ThinkPad X1 Carbon 7th gen',
    category: 'laptops',
    basePrice: 30000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Бизнес-класс, вес меньше килограмма', 'Карбоновый корпус, без трещин', 'Для работы идеально, всё летает'],
  },
  {
    key: 'asus-tuf-f15',
    title: 'ASUS TUF Gaming F15 (RTX 3060)',
    category: 'laptops',
    basePrice: 58000,
    jitter: 0.18,
    weight: 1.5,
    desc: ['Игровой, 144 Гц, видеокарта не душится', 'Чищен, термопаста свежая', 'Сумка и зарядка в комплекте'],
  },
  {
    key: 'acer-nitro-5',
    title: 'Acer Nitro 5 (GTX 1650)',
    category: 'laptops',
    basePrice: 44000,
    jitter: 0.2,
    weight: 1.6,
    desc: ['Тянет всё на высоких, проверено', 'Клава с подсветкой, шумит умеренно', 'Продаю, взял себе стационар'],
  },
  {
    key: 'msi-gf63',
    title: 'MSI GF63 Thin',
    category: 'laptops',
    basePrice: 46000,
    jitter: 0.2,
    weight: 0.8,
    desc: ['Тонкий игровой, для учёбы и игр хватит', 'Экран без битых пикселей', 'Небольшой люфт крышки, на работу не влияет'],
  },
  {
    key: 'hp-pavilion-15',
    title: 'HP Pavilion 15',
    category: 'laptops',
    basePrice: 24000,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Для учёбы и фильмов самое то', 'Аккум три часа спокойно', 'Мелкие царапки на крышке'],
  },
  {
    key: 'lenovo-ideapad-3',
    title: 'Lenovo IdeaPad 3',
    category: 'laptops',
    basePrice: 17500,
    jitter: 0.22,
    weight: 1.8,
    desc: ['Рабочая лошадка, ничего не лагает', 'Куплен для универа, диплом защищён', 'Комплект как из магазина'],
  },
  {
    key: 'dell-latitude-7490',
    title: 'Dell Latitude 7490',
    category: 'laptops',
    basePrice: 19500,
    jitter: 0.22,
    weight: 0.8,
    desc: ['Корпоративный, обслуженный', 'Аккум держит как новый', 'Металлический корпус, без люфтов'],
  },
  {
    key: 'huawei-matebook-d15',
    title: 'Huawei MateBook D15',
    category: 'laptops',
    basePrice: 28000,
    jitter: 0.2,
    desc: ['Экран красивый, рамки тонкие', 'Всё штатно, система чистая', 'Продаю из-за перехода на макбук'],
  },
  {
    key: 'asus-vivobook-15',
    title: 'ASUS VivoBook 15',
    category: 'laptops',
    basePrice: 21500,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Лёгкий, для учёбы идеален', 'Царапина на крышке, экран цел', 'Зарядное в комплекте'],
  },
  {
    key: 'macbook-air-2017',
    title: 'MacBook Air 13" 2017',
    category: 'laptops',
    basePrice: 17000,
    jitter: 0.25,
    weight: 0.8,
    desc: ['Рабочая лошадка для браузера и текстов', 'Аккум циклов 400, держит три часа', 'Пара вмятинок на углу, всё работает'],
  },

  // ---------------- Электроника ----------------
  {
    key: 'ps5',
    title: 'PlayStation 5 (с дисководом)',
    category: 'electronics',
    basePrice: 42000,
    jitter: 0.15,
    weight: 2.5,
    desc: [
      'Дисковод читает всё, вентилятор тихий',
      'Ухоженная, геймпад без люфта',
      'Шнур HDMI в комплекте',
      'Взял второй, это запасная',
    ],
  },
  {
    key: 'ps4-slim',
    title: 'PlayStation 4 Slim 500GB',
    category: 'electronics',
    basePrice: 13500,
    jitter: 0.2,
    weight: 2,
    desc: ['Читает диски, шумит в меру', 'Пять игр в подарок', 'Геймпад родной, стики без люфта'],
  },
  {
    key: 'xbox-series-s',
    title: 'Xbox Series S 512GB',
    category: 'electronics',
    basePrice: 19500,
    jitter: 0.2,
    desc: ['Компактная, всё работает', 'Геймпад целый, батарейки в подарок', 'Продаю, перешёл на плейстейшн'],
  },
  {
    key: 'nintendo-switch',
    title: 'Nintendo Switch',
    category: 'electronics',
    basePrice: 18000,
    jitter: 0.2,
    weight: 1.8,
    desc: ['Док, зарядка и чехол в комплекте', 'Джойсты не дрифтят, проверено', 'Экран под плёнкой с первого дня'],
  },
  {
    key: 'airpods-pro-2',
    title: 'AirPods Pro 2',
    category: 'electronics',
    basePrice: 12000,
    jitter: 0.18,
    weight: 2.2,
    desc: ['Оригинал, проверка по серийнику', 'Аккум держит как в день покупки', 'Кейс без сколов, амбушюры новые'],
  },
  {
    key: 'apple-watch-7',
    title: 'Apple Watch Series 7 45mm',
    category: 'electronics',
    basePrice: 15000,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Аккум день спокойно', 'Стекло целое, второй ремешок в подарок', 'Коробка и зарядка на месте'],
  },
  {
    key: 'galaxy-watch-4',
    title: 'Samsung Galaxy Watch4 44mm',
    category: 'electronics',
    basePrice: 7500,
    jitter: 0.25,
    weight: 0.8,
    desc: ['Состояние хорошее, стекло целое', 'Датчики работают, аккум норм', 'Два ремешка в подарок'],
  },
  {
    key: 'yandex-station-mini',
    title: 'Яндекс Станция Мини',
    category: 'electronics',
    basePrice: 4200,
    jitter: 0.2,
    weight: 2,
    desc: ['Работает идеально, звук приятный', 'Куплена лишняя, стоит без дела', 'Кабель в комплекте'],
  },
  {
    key: 'tv-samsung-43',
    title: 'Телевизор Samsung 43" 4K',
    category: 'electronics',
    basePrice: 26000,
    jitter: 0.2,
    weight: 1.6,
    desc: ['Матрица без битых пикселей', 'Пульт и ножки в комплекте', 'Висел в спальне, смотрели мало'],
  },
  {
    key: 'monitor-lg-24',
    title: 'Монитор LG 24" IPS 75Hz',
    category: 'electronics',
    basePrice: 7200,
    jitter: 0.22,
    weight: 1.6,
    desc: ['Битых пикселей нет, подсветка ровная', 'Для учёбы и работы идеален', 'Под кронштейн VESA'],
  },
  {
    key: 'sony-wh-1000xm4',
    title: 'Наушники Sony WH-1000XM4',
    category: 'electronics',
    basePrice: 14000,
    jitter: 0.2,
    desc: ['Шумодав работает как новый', 'Амбушюры целые, чехол в комплекте', 'Аккум держит сутки'],
  },
  {
    key: 'keychron-k2',
    title: 'Клавиатура Keychron K2',
    category: 'electronics',
    basePrice: 5800,
    jitter: 0.25,
    weight: 0.6,
    desc: ['Свитчи брауны, стук приятный', 'Все клавиши работают', 'Смотрится на столе отлично'],
  },

  // ---------------- Одежда ----------------
  {
    key: 'puhovik-uniqlo',
    title: 'Пуховик Uniqlo Ultra Light Down',
    category: 'clothes',
    basePrice: 3800,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Лёгкий, тёплый до минус двадцати', 'Носил один сезон, постиран', 'Размер M, на 48-50'],
  },
  {
    key: 'tnf-kurtka',
    title: 'Зимняя куртка The North Face',
    category: 'clothes',
    basePrice: 12000,
    jitter: 0.25,
    desc: ['Мембрана живая, капюшон цел', 'Оригинал, куплена в фирменном', 'Ношена пару сезонов, состояние супер'],
  },
  {
    key: 'levis-501',
    title: 'Джинсы Levi\'s 501',
    category: 'clothes',
    basePrice: 3400,
    jitter: 0.3,
    weight: 2,
    desc: ['Оригинал, строчка ровная', 'Посадка идеальная, размер 32', 'Носка минимальная, без потёртостей'],
  },
  {
    key: 'zara-hoodie',
    title: 'Худи Zara oversize',
    category: 'clothes',
    basePrice: 1700,
    jitter: 0.35,
    weight: 1.8,
    desc: ['Оверсайз, хлопок плотный', 'Одевала пару раз, как новое', 'Размер S, на рост 165'],
  },
  {
    key: 'massimo-palto',
    title: 'Пальто Massimo Dutti',
    category: 'clothes',
    basePrice: 6500,
    jitter: 0.28,
    weight: 0.8,
    desc: ['Шерсть, сидит идеально', 'Продаю, гардероб меняется', 'Химчистка сделана, носки почти нет'],
  },
  {
    key: 'henderson-kostyum',
    title: 'Костюм Henderson',
    category: 'clothes',
    basePrice: 8000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Одевал на встречи, состояние отличное', 'Подшит под рост 180, брюки 32', 'Чехол в подарок'],
  },
  {
    key: 'mango-dress',
    title: 'Платье Mango',
    category: 'clothes',
    basePrice: 1900,
    jitter: 0.35,
    weight: 1.5,
    desc: ['Лёгкое, для лета идеально', 'Одевала один раз на свадьбу', 'Размер XS-S'],
  },
  {
    key: 'carhartt-detroit',
    title: 'Куртка Carhartt WIP Detroit',
    category: 'clothes',
    basePrice: 9000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Канвас плотный, заломы красивые', 'Оригинал, покупал в профильном магазине', 'Сел идеально, но стиль сменился'],
  },
  {
    key: 'tommy-tishka',
    title: 'Футболка Tommy Hilfiger',
    category: 'clothes',
    basePrice: 1700,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Хлопок, не растянулась', 'Машинная стирка, принт целый', 'Размер L'],
  },
  {
    key: 'adidas-sportcost',
    title: 'Спортивный костюм Adidas',
    category: 'clothes',
    basePrice: 3400,
    jitter: 0.3,
    weight: 1.6,
    desc: ['Трикотаж живой, молния работает', 'Носил на пробежки, постиран', 'Размер L, на рост 180'],
  },
  {
    key: 'polushubok',
    title: 'Полушубок овчинный',
    category: 'clothes',
    basePrice: 8500,
    jitter: 0.3,
    weight: 0.5,
    desc: ['Овчина тёплая, молния новая', 'Хранился в чехле, без моли', 'Размер 50-52, забирайте до холодов'],
  },

  // ---------------- Кроссовки ----------------
  {
    key: 'nike-af1',
    title: 'Nike Air Force 1 \'07',
    category: 'sneakers',
    basePrice: 6000,
    jitter: 0.22,
    weight: 2.5,
    desc: ['Белые, отстирал до состояния новых', 'Подошва не отклеивается, всё цело', 'Размер 42 US 9, померить можно'],
  },
  {
    key: 'adidas-samba',
    title: 'Adidas Samba OG',
    category: 'sneakers',
    basePrice: 8000,
    jitter: 0.2,
    weight: 1.8,
    desc: ['Оригинал, коробка сохранилась', 'Замша целая, подошва чистая', 'Носил месяц всего'],
  },
  {
    key: 'nb-574',
    title: 'New Balance 574',
    category: 'sneakers',
    basePrice: 5300,
    jitter: 0.22,
    weight: 1.6,
    desc: ['Классика, сидят идеально', 'Стельки новые, носок лёгкий', 'Размер 43'],
  },
  {
    key: 'aj1-mid',
    title: 'Air Jordan 1 Mid',
    category: 'sneakers',
    basePrice: 11500,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Состояние близкое к идеалу', 'Коробка и чек есть', 'Носил только в сухую погоду'],
  },
  {
    key: 'asics-kayano-14',
    title: 'Asics Gel-Kayano 14',
    category: 'sneakers',
    basePrice: 8800,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Модель снова в моде, забирайте', 'Сетка целая, подошва не раскрошилась', 'Оригинал, размер 42.5'],
  },
  {
    key: 'puma-suede',
    title: 'Puma Suede Classic',
    category: 'sneakers',
    basePrice: 3400,
    jitter: 0.28,
    desc: ['Замша бархатная, без задиров', 'Ношены сезон, состояние хорошее', 'Размер 41'],
  },
  {
    key: 'reebok-classic',
    title: 'Reebok Classic Leather',
    category: 'sneakers',
    basePrice: 3300,
    jitter: 0.28,
    desc: ['Кожа мягкая, швы ровные', 'Классика на каждый день', 'Размер 44, маломерят на полразмера'],
  },
  {
    key: 'salomon-xt6',
    title: 'Salomon XT-6',
    category: 'sneakers',
    basePrice: 11000,
    jitter: 0.2,
    weight: 0.7,
    desc: ['Горная классика, состояние топ', 'Быстрая шнуровка работает чётко', 'Размер 43, оригинал'],
  },
  {
    key: 'vans-old-skool',
    title: 'Vans Old Skool',
    category: 'sneakers',
    basePrice: 3900,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Подошва держится крепко, ничего не отклеилось', 'Канвас без дырок, полосы целые', 'Размер 42'],
  },

  // ---------------- Мебель ----------------
  {
    key: 'divan-knizhka',
    title: 'Диван-книжка',
    category: 'furniture',
    basePrice: 5500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Механизм рабочий, спится отлично', 'Каркас крепкий, чехол постиран', 'Забрать до пятницы, освобождаю комнату'],
  },
  {
    key: 'friheten',
    title: 'Угловой диван IKEA Friheten',
    category: 'furniture',
    basePrice: 17500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Раскладывается, внутри ящик для белья', 'Чехол снимается и стирается', 'Служил три года, продаю из-за переезда'],
  },
  {
    key: 'bean-bag',
    title: 'Кресло-мешок',
    category: 'furniture',
    basePrice: 1800,
    jitter: 0.35,
    desc: ['Наполнитель не слежался', 'Чехол постиран, как новый', 'Отдам вместе с пуфом, если заберёте всё'],
  },
  {
    key: 'komod-sosna',
    title: 'Комод из массива сосны',
    category: 'furniture',
    basePrice: 4200,
    jitter: 0.3,
    desc: ['Массив, ящики ходят ровно', 'Небольшие следы использования', 'Подойдёт для дачи или детской'],
  },
  {
    key: 'komp-stol',
    title: 'Компьютерный стол',
    category: 'furniture',
    basePrice: 2400,
    jitter: 0.32,
    weight: 1.5,
    desc: ['Полка под клавиатуру выдвигается', 'Стабильный, не шатается', 'Разобрать помогу, крепёж цел'],
  },
  {
    key: 'shkaf-kupe',
    title: 'Шкаф-купе три двери',
    category: 'furniture',
    basePrice: 8500,
    jitter: 0.3,
    desc: ['Зеркала без сколов', 'Внутри штанга, полки и ящики', 'Разберём и вынесем сами'],
  },
  {
    key: 'krovat-160',
    title: 'Кровать 160х200 с основанием',
    category: 'furniture',
    basePrice: 7800,
    jitter: 0.3,
    desc: ['Основание ортопедическое, ламели целые', 'Матрас продам отдельно, если нужно', 'Каркас без сколов и трещин'],
  },
  {
    key: 'eames-kreslo',
    title: 'Кресло в стиле Eames',
    category: 'furniture',
    basePrice: 5200,
    jitter: 0.28,
    weight: 0.6,
    desc: ['Кожзам цел, ножки хромированные', 'Смотрится в интерьере дорого', 'Стилистика комнаты поменялась, продаю'],
  },
  {
    key: 'billy',
    title: 'Стеллаж IKEA Billy',
    category: 'furniture',
    basePrice: 2300,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Полки ровные, крепёж полный', 'Цвет белый, выцветания нет', 'Разобран, забирать удобно'],
  },

  // ---------------- Бытовая техника ----------------
  {
    key: 'robot-xiaomi',
    title: 'Робот-пылесос Xiaomi',
    category: 'appliances',
    basePrice: 9000,
    jitter: 0.2,
    weight: 2,
    desc: ['Датчики чистые, ездит по плану', 'Аккум убирает три комнаты', 'Контейнер и щётки в комплекте'],
  },
  {
    key: 'atlant-holodilnik',
    title: 'Холодильник Атлант двухкамерный',
    category: 'appliances',
    basePrice: 12000,
    jitter: 0.25,
    desc: ['Морозит отлично, морозилка держит лёд', 'Куплен пять лет назад, обслужен', 'Дверцы перевешиваются, зазоры ровные'],
  },
  {
    key: 'lg-stiralka',
    title: 'Стиральная машина LG 6 кг',
    category: 'appliances',
    basePrice: 10500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Прямой привод, шумит мало', 'ТЭН рабочий, стирала регулярно', 'Заливной шланг в комплекте'],
  },
  {
    key: 'svch-samsung',
    title: 'Микроволновка Samsung 23 л',
    category: 'appliances',
    basePrice: 2900,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Греет ровно, дверца прилегает', 'Эмаль внутри целая', 'Стояла на даче, включали пару раз'],
  },
  {
    key: 'multivarka-redmond',
    title: 'Мультиварка Redmond',
    category: 'appliances',
    basePrice: 2400,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Чаша без царапин, клапан целый', 'Книжку рецептов приложу', 'Продаю из-за переезда'],
  },
  {
    key: 'dyson-v8',
    title: 'Пылесос Dyson V8',
    category: 'appliances',
    basePrice: 12000,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Аккум живой, тянет двадцать минут в турбо', 'Фильтр промыт, насадки все', 'Настенный док в подарок'],
  },
  {
    key: 'delonghi-kofemashina',
    title: 'Кофемашина DeLonghi',
    category: 'appliances',
    basePrice: 14500,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Капучинатор работает, накипи нет', 'Чищена по инструкции', 'Готовит эспрессо как в кофейне'],
  },
  {
    key: 'bosch-duhovka',
    title: 'Духовка Bosch встраиваемая',
    category: 'appliances',
    basePrice: 8500,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Нагрев ровный, конвекция работает', 'Стекло без трещин, решётки целые', 'Снимается при замене кухни'],
  },
  {
    key: 'noirot-konvektor',
    title: 'Конвектор Noirot 1000 Вт',
    category: 'appliances',
    basePrice: 2900,
    jitter: 0.3,
    weight: 0.8,
    desc: ['Греет быстро, терморегулятор точный', 'Один сезон работы', 'Кабель целый, крепления на стену есть'],
  },

  // ---------------- Хобби и отдых ----------------
  {
    key: 'xiaomi-m365',
    title: 'Электросамокат Xiaomi M365',
    category: 'hobby',
    basePrice: 11500,
    jitter: 0.22,
    weight: 1.8,
    desc: ['Пробег небольшой, ездил по вечерам', 'Аккум живой, тормоза настроены', 'Камеры менял в прошлом сезоне'],
  },
  {
    key: 'stels-navigator',
    title: 'Велосипед Stels Navigator',
    category: 'hobby',
    basePrice: 7500,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Переключается ровно, тормоза новые', 'Катался два сезона, хранился в гараже', 'Крылья и багажник в комплекте'],
  },
  {
    key: 'karkasson',
    title: 'Настольная игра Каркассон',
    category: 'hobby',
    basePrice: 1400,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Все фишки и карточки на месте', 'Коробка целая, правила есть', 'Играли всей семьёй, отходим от настолок'],
  },
  {
    key: 'palatka-3',
    title: 'Палатка 3-местная',
    category: 'hobby',
    basePrice: 3300,
    jitter: 0.3,
    desc: ['Дождь держала, проверено', 'Швы проклеены, дуги целые', 'Ходили в неё дважды'],
  },
  {
    key: 'aquarium-60',
    title: 'Аквариум 60 л с тумбой',
    category: 'hobby',
    basePrice: 2800,
    jitter: 0.35,
    weight: 0.5,
    desc: ['Стёкла без сколов, швы герметичны', 'Фильтр и лампа в подарок', 'Рыб раздал, продаю пустым'],
  },
  {
    key: 'dualshock-4',
    title: 'Геймпад DualShock 4',
    category: 'hobby',
    basePrice: 2400,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Стики без люфта, отзыв живой', 'Аккум держит как новый', 'Шнур зарядки в комплекте'],
  },
  {
    key: 'garmin-etrex',
    title: 'Навигатор Garmin eTrex',
    category: 'hobby',
    basePrice: 4800,
    jitter: 0.3,
    weight: 0.4,
    desc: ['Спутники ловит быстро, корпус целый', 'Работает от батареек АА', 'Карта России загружена'],
  },
  {
    key: 'teleskop-skywatcher',
    title: 'Телескоп Sky-Watcher 707',
    category: 'hobby',
    basePrice: 8500,
    jitter: 0.3,
    weight: 0.4,
    desc: ['Оптика чистая, без царапин', 'Штатив устойчивый, всё в комплекте', 'Смотрели Луну и Сатурн, кольца видно'],
  },
  {
    key: 'metalloiskatel-xterra',
    title: 'Металлоискатель X-Terra 305',
    category: 'hobby',
    basePrice: 16000,
    jitter: 0.3,
    weight: 0.4,
    desc: ['Катушка штатная, дискриминация работает', 'Выходил с ним каждые выходные', 'Батарейный отсек сухой, коррозии нет'],
  },

  // ---------------- Спорт ----------------
  {
    key: 'ganteli-16',
    title: 'Гантели разборные 2х16 кг',
    category: 'sport',
    basePrice: 3400,
    jitter: 0.28,
    weight: 1.6,
    desc: ['Блины сидят плотно, гайки целые', 'Ручки обрезинены, руки не натирают', 'Забирай, места в квартире нет'],
  },
  {
    key: 'shtanga-50',
    title: 'Штанга с блинами 50 кг',
    category: 'sport',
    basePrice: 4800,
    jitter: 0.28,
    desc: ['Гриф ровный, блины чугунные', 'Замки-защёлки в комплекте', 'Отдам вместе с лямками'],
  },
  {
    key: 'begovaya-dorozhka',
    title: 'Беговая дорожка электрическая',
    category: 'sport',
    basePrice: 14500,
    jitter: 0.25,
    desc: ['Складывается, мотор не шумит', 'Полотно не проскальзывает', 'Пробег небольшой, смотрится прилично'],
  },
  {
    key: 'velotrenazher',
    title: 'Велотренажёр магнитный',
    category: 'sport',
    basePrice: 7500,
    jitter: 0.28,
    desc: ['Восемь уровней нагрузки', 'Сиденье регулируется, педали целые', 'Стояла без дела, отдаю дешевле'],
  },
  {
    key: 'burton-custom',
    title: 'Сноуборд Burton Custom 158',
    category: 'sport',
    basePrice: 14000,
    jitter: 0.25,
    weight: 0.5,
    desc: ['Кант цел, скользяк без глубоких царапин', 'Крепления отдам в подарок', 'Доска живая, проверена в горах'],
  },
  {
    key: 'bauer-konki',
    title: 'Коньки хоккейные Bauer',
    category: 'sport',
    basePrice: 3800,
    jitter: 0.3,
    weight: 0.8,
    desc: ['Лезвия затачены, ботинок держит голеностоп', 'Размер 43, шнуровка новая', 'Ходили два сезона в коробку'],
  },
  {
    key: 'rollerblade',
    title: 'Ролики Rollerblade',
    category: 'sport',
    basePrice: 3300,
    jitter: 0.3,
    desc: ['Колёса 80 мм, подшипники живые', 'Тормоз на месте, рама ровная', 'Размер 42-43'],
  },
  {
    key: 'wilson-raketki',
    title: 'Теннисные ракетки Wilson (2 шт)',
    category: 'sport',
    basePrice: 3800,
    jitter: 0.3,
    weight: 0.5,
    desc: ['Струны свежие, обмотка целая', 'Чехлы в комплекте', 'Брал для пары игр на корте, дальше пылятся'],
  },
  {
    key: 'turnik',
    title: 'Турник настенный',
    category: 'sport',
    basePrice: 1400,
    jitter: 0.32,
    weight: 1.5,
    desc: ['Держит сто двадцать, проверено мной', 'Порошковая покраска, без ржавчины', 'Крепёж полный, анкеры в комплекте'],
  },

  // ---------------- Музыка ----------------
  {
    key: 'fender-strat-mex',
    title: 'Fender Stratocaster (Мексика)',
    category: 'music',
    basePrice: 33000,
    jitter: 0.2,
    weight: 0.7,
    desc: ['Звук живой, электроника родная', 'Гриф ровный, строит по всей длине', 'Кейс в подарок'],
  },
  {
    key: 'yamaha-f310',
    title: 'Гитара Yamaha F310',
    category: 'music',
    basePrice: 6500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Лучшая гитара для старта', 'Струны новые, гриф ровный', 'Звук громкий и тёплый'],
  },
  {
    key: 'yamaha-psr-e373',
    title: 'Синтезатор Yamaha PSR-E373',
    category: 'music',
    basePrice: 13500,
    jitter: 0.22,
    desc: ['Клавиши полувзвешенные, всё отзывчивое', 'Куча тембров и автоаккомпанемент', 'Адаптер в комплекте, стенд отдельно'],
  },
  {
    key: 'at-lp60x',
    title: 'Проигрыватель Audio-Technica LP60X',
    category: 'music',
    basePrice: 8800,
    jitter: 0.22,
    weight: 0.8,
    desc: ['Полностью автомат, иглу менял недавно', 'Крутит ровно, фон минимальный', 'Лучший старт для винильщика'],
  },
  {
    key: 'vinil-20',
    title: 'Виниловые пластинки (20 шт)',
    category: 'music',
    basePrice: 3800,
    jitter: 0.35,
    weight: 0.7,
    desc: ['Состояние от хорошего до отличного', 'Рок и поп, список пришлю', 'Отдам всё сразу, по одной не разбирать'],
  },
  {
    key: 'squier-strat',
    title: 'Электрогитара Squier Strat',
    category: 'music',
    basePrice: 9500,
    jitter: 0.22,
    desc: ['Для учёбы идеальна, звук ровный', 'Ручки не хрустят, розетка родная', 'Ремешок и медиаторы в подарок'],
  },
  {
    key: 'fender-champion-20',
    title: 'Комбоусилитель Fender Champion 20',
    category: 'music',
    basePrice: 7800,
    jitter: 0.25,
    weight: 0.6,
    desc: ['Двенадцать эффектов, чистый звук приятный', 'Громкости хватает на комнату и гараж', 'Работал без нареканий'],
  },
  {
    key: 'ukulele',
    title: 'Укулеле concert',
    category: 'music',
    basePrice: 1900,
    jitter: 0.3,
    weight: 0.7,
    desc: ['Нейлон мягкий, пальцам комфортно', 'Строй держит, колки не проскальзывают', 'Чехол в подарок, брал для поездок'],
  },

  // ---------------- Авто и мото ----------------
  {
    key: 'nokian-8',
    title: 'Шины Nokian Hakkapeliitta 8 (4 шт)',
    category: 'auto',
    basePrice: 17000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Шипы почти все на месте, протектор 7 мм', 'Хранились в сухом гараже', 'Продаю в связи со сменой машины'],
  },
  {
    key: 'advocam',
    title: 'Видеорегистратор AdvoCam FD7',
    category: 'auto',
    basePrice: 3200,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Пишет чётко и днём и ночью', 'Крепление на присоске, кабель есть', 'Снял с проданной машины'],
  },
  {
    key: 'pioneer-2din',
    title: 'Магнитола Pioneer 2DIN',
    category: 'auto',
    basePrice: 5800,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Экран живой, сенсор отзывчивый', 'Bluetooth работает, микрофон в комплекте', 'Подходит на большинство иномарок'],
  },
  {
    key: 'domkrat-2t',
    title: 'Домкрат подкатной 2т',
    category: 'auto',
    basePrice: 1300,
    jitter: 0.3,
    desc: ['Поднимает уверенно, клапан не травит', 'Масло не подтекает', 'Лежал в багажнике, рабочее состояние'],
  },
  {
    key: 'poperechniny',
    title: 'Поперечины на крышу',
    category: 'auto',
    basePrice: 3800,
    jitter: 0.3,
    weight: 0.6,
    desc: ['Сталь, замки целые', 'Подходили на Kia Ceed', 'Ключи в комплекте'],
  },
  {
    key: 'avtokompressor',
    title: 'Автомобильный компрессор',
    category: 'auto',
    basePrice: 1500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Накачивает колесо за три минуты', 'Шланг и насадки на месте', 'Проверен перед продажей'],
  },
  {
    key: 'diski-r16',
    title: 'Литые диски R16 (4 шт)',
    category: 'auto',
    basePrice: 7800,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Балансировка нормальная, кривых нет', 'Подходили на Ford Focus', 'Покрышки не продаю, только диски'],
  },
  {
    key: 'hjc-shlem',
    title: 'Мотошлем HJC',
    category: 'auto',
    basePrice: 4800,
    jitter: 0.28,
    weight: 0.6,
    desc: ['Стекло без царапин, подкладка целая', 'Размер L, застёжка работает', 'Не падал, куплен в мотосалоне'],
  },

  // ---------------- Детское ----------------
  {
    key: 'anex-kolyaska',
    title: 'Коляска Anex 2 в 1',
    category: 'kids',
    basePrice: 11500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Колёса целые, механизм складывания чёткий', 'Комплект: люлька и прогулка, дождевик', 'После одного ребёнка, всё помыто'],
  },
  {
    key: 'britax-kreslo',
    title: 'Автокресло Britax Römer',
    category: 'kids',
    basePrice: 5800,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Крепление изофикс, ремни целые', 'После аварий не было', 'Чехол постиран'],
  },
  {
    key: 'det-krovatka',
    title: 'Детская кроватка с матрасом',
    category: 'kids',
    basePrice: 3300,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Борта целые, планки надёжные', 'Матрас покупали недавно', 'Разбирается, перевозка простая'],
  },
  {
    key: 'vel-16',
    title: 'Велосипед детский 16"',
    category: 'kids',
    basePrice: 2800,
    jitter: 0.3,
    weight: 1.5,
    desc: ['На рост ребёнка 105-115', 'Помощные колёсики в комплекте', 'Цепь смазана, тормоз работает'],
  },
  {
    key: 'fisher-price',
    title: 'Развивающий центр Fisher-Price',
    category: 'kids',
    basePrice: 1700,
    jitter: 0.32,
    desc: ['Всё мигает и играет, батарейки свои', 'Пластик вымыт, ничего не отломано', 'Дочка выросла, отдаю дешевле'],
  },
  {
    key: 'lego-razves',
    title: 'Конструктор LEGO на развес (2 кг)',
    category: 'kids',
    basePrice: 2200,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Все детали целые, есть фигурки', 'Отмыты, отдам в пакете', 'Инструкции не сохранялись'],
  },
  {
    key: 'sanki-kanadka',
    title: 'Санки «Канадка»',
    category: 'kids',
    basePrice: 1100,
    jitter: 0.3,
    weight: 0.8,
    desc: ['Полозья ровные, спинка целая', 'Ремень безопасности на месте', 'Забирайте до снега, зима близко'],
  },

  // ---------------- Книги ----------------
  {
    key: 'master-margarita',
    title: 'Булгаков «Мастер и Маргарита» (илл. изд.)',
    category: 'books',
    basePrice: 650,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Иллюстрированное издание, твёрдый переплёт', 'Страницы без подчёркиваний', 'Бережно хранилась'],
  },
  {
    key: 'hp-set',
    title: 'Гарри Поттер, все 7 томов (Росмэн)',
    category: 'books',
    basePrice: 3200,
    jitter: 0.25,
    desc: ['Все семь томов, издательство Росмэн', 'Обложки целые, корешки аккуратные', 'Продаю коллекцию целиком'],
  },
  {
    key: 'voina-i-mir',
    title: 'Толстой «Война и мир», 2 тома',
    category: 'books',
    basePrice: 380,
    jitter: 0.3,
    desc: ['Классическое издание, два тома', 'Блок цел, страницы чистые', 'Читал один раз'],
  },
  {
    key: 'fant-15',
    title: 'Фантастика, 15 книг (Стругацкие и др.)',
    category: 'books',
    basePrice: 850,
    jitter: 0.3,
    weight: 0.8,
    desc: ['Стругацкие, Лем, Саймак и другие', 'Издания девяностых, состояние разное', 'Отдам всё разом, по одной не продам'],
  },
  {
    key: 'enc-detskaya',
    title: 'Детская энциклопедия «Хочу всё знать»',
    category: 'books',
    basePrice: 450,
    jitter: 0.3,
    desc: ['Красочные иллюстрации, твёрдый переплёт', 'Ребёнок вырос, книга целая', 'Пять томов, все на месте'],
  },
  {
    key: 'biznes-5',
    title: 'Бизнес-литература, 5 книг',
    category: 'books',
    basePrice: 650,
    jitter: 0.3,
    desc: ['Кийосаки, Трейси и другие', 'Читаны один раз, без пометок', 'Отдам пачкой, пригодится начинающим'],
  },
  {
    key: 'marvel-12',
    title: 'Комиксы Marvel (12 выпусков)',
    category: 'books',
    basePrice: 800,
    jitter: 0.3,
    weight: 0.5,
    desc: ['Двенадцать выпусков, состояние хорошее', 'Без вырезанных страниц', 'Отдам коллекционеру дешевле'],
  },

  // ---------------- МУСОР: объявления «Отдам даром» ----------------
  {
    key: 'trash-stul',
    title: 'Стул сломанный, отдам даром',
    category: 'furniture',
    basePrice: 150,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Отдам даром, сломана ножка', 'Кто с руками — починит за вечер', 'Стоит у подъезда, самовывоз'],
  },
  {
    key: 'trash-monitor',
    title: 'Монитор битый, отдам даром',
    category: 'electronics',
    basePrice: 300,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Трещина на матрице, не включается', 'Отдам даром на запчасти', 'Заберите, пылится на балконе'],
  },
  {
    key: 'trash-velosiped',
    title: 'Велосипед ржавый без цепи, отдам даром',
    category: 'hobby',
    basePrice: 400,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Отдам даром, ржавый и без цепи', 'Колёса и рама целые, остальное под вопросом', 'Забирайте из гаража'],
  },
  {
    key: 'trash-mikrovolnovka',
    title: 'Микроволновка старая, не работает, отдам даром',
    category: 'appliances',
    basePrice: 200,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Не греет, отдам даром', 'Может пригодиться мастеру или на запчасти', 'Забирайте, места нет'],
  },
  {
    key: 'trash-divan',
    title: 'Диван порванный, отдам даром',
    category: 'furniture',
    basePrice: 450,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Обивка порвана, каркас крепкий', 'Отдам даром, помогу вынести', 'На дачу или на запчасти подойдёт'],
  },
  {
    key: 'trash-printer',
    title: 'Принтер старый, отдам даром',
    category: 'electronics',
    basePrice: 250,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Не печатает, отдам даром', 'Пусть будет донором', 'Забирайте до вечера, потом на мусорку'],
  },
  {
    key: 'trash-naushniki',
    title: 'Наушники без левого канала, отдам даром',
    category: 'electronics',
    basePrice: 150,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Левый канал умер, отдам даром', 'Провод целый, звук в правом есть', 'Забирайте смело, дефект честно пишу'],
  },
  {
    key: 'trash-rc-mashina',
    title: 'Машина на радиоуправлении не едет, отдам даром',
    category: 'hobby',
    basePrice: 200,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Не едет, отдам даром', 'Мотор возможно живой, пульт в комплекте', 'Кому на запчасти или ребёнку на корпус'],
  },
]
