// Данные каталога товаров. Типы — в catalog-types.ts
// Цены — средний рынок б/у РФ для состояния good, в рублях.

import type { CatalogItem } from './catalog-types'

export const CATALOG: CatalogItem[] = [
  // ---------------- Телефоны ----------------
  {
    key: 'iphone-12',
    title: 'iPhone 12 64GB',
    category: 'phones',
    basePrice: 28000,
    jitter: 0.2,
    weight: 2.5,
    desc: [
      'Аккум 85%, всё работает как надо',
      'В чехле и со стеклом с первого дня',
      'Коробка и кабель в комплекте, чек есть',
    ],
  },
  {
    key: 'iphone-11',
    title: 'iPhone 11 64GB',
    category: 'phones',
    basePrice: 19000,
    jitter: 0.2,
    weight: 2.2,
    desc: ['Аккум 82%, держит до вечера', 'Мелкие царапки на рамке, экран цел', 'Продаю из-за апгрейда'],
  },
  {
    key: 'iphone-13',
    title: 'iPhone 13 128GB',
    category: 'phones',
    basePrice: 40000,
    jitter: 0.18,
    weight: 2,
    desc: ['Состояние почти нового, аккум 91%', 'Куплен в официальном магазине', 'Комплект полный, чек сохранён'],
  },
  {
    key: 'iphone-xr',
    title: 'iPhone XR 64GB',
    category: 'phones',
    basePrice: 11500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Батарея живая, держит день', 'Скол на углу корпуса, экран без битых пикселей', 'Только телефон, без коробки'],
  },
  {
    key: 'iphone-se-2020',
    title: 'iPhone SE 2020 64GB',
    category: 'phones',
    basePrice: 9500,
    jitter: 0.25,
    desc: ['Компактный, как из коробки', 'Аккум 88%, Touch ID работает чётко', 'Идеален как второй телефон'],
  },
  {
    key: 'galaxy-s22',
    title: 'Samsung Galaxy S22 128GB',
    category: 'phones',
    basePrice: 35000,
    jitter: 0.2,
    weight: 2,
    desc: ['Амолед яркий, выгораний нет', 'Прошивка официальная, ничего не перепрошивал', 'Пара потёртостей на рамке, экран идеален'],
  },
  {
    key: 'galaxy-s21',
    title: 'Samsung Galaxy S21 128GB',
    category: 'phones',
    basePrice: 23000,
    jitter: 0.22,
    weight: 1.8,
    desc: ['Плёнка с первого дня, экран без царапин', 'Аккум 83%', 'Ухоженный, без вмятин и сколов'],
  },
  {
    key: 'galaxy-a54',
    title: 'Samsung Galaxy A54',
    category: 'phones',
    basePrice: 16000,
    jitter: 0.18,
    weight: 2.2,
    desc: ['Полгода пользовался, как новый', 'Батарея огромная, хватает на два дня', 'Чек и коробка на месте'],
  },
  {
    key: 'redmi-note-12',
    title: 'Xiaomi Redmi Note 12 128GB',
    category: 'phones',
    basePrice: 8500,
    jitter: 0.22,
    weight: 2.5,
    desc: ['Родной чехол в комплекте', 'Всё работает без нареканий', 'Продаю, потому что взял себе флагман'],
  },
  {
    key: 'poco-x5-pro',
    title: 'Poco X5 Pro 256GB',
    category: 'phones',
    basePrice: 11500,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Игровой проц, всё тянёт', 'Царапина на крышке, экран идеален', 'Зарядка быстрая, шнур в комплекте'],
  },
  {
    key: 'realme-gt-neo-3',
    title: 'Realme GT Neo 3',
    category: 'phones',
    basePrice: 12500,
    jitter: 0.25,
    desc: ['Заряжается с нуля за сорок минут', 'Кнопки не люфтят, состояние хорошее', 'Без коробки, только шнур'],
  },
  {
    key: 'pixel-6a',
    title: 'Google Pixel 6a',
    category: 'phones',
    basePrice: 14000,
    jitter: 0.3,
    weight: 0.5,
    desc: ['Привезён из Германии, ловит наши сети отлично', 'Чистый андроид, обновления приходят', 'Камера топовая, состояние отличное'],
  },
  {
    key: 'huawei-p30-pro',
    title: 'Huawei P30 Pro',
    category: 'phones',
    basePrice: 10000,
    jitter: 0.28,
    weight: 0.7,
    desc: ['Зум как у подзорной трубы', 'Без сервисов гугла, всё настроено и работает', 'Корпус в идеале, стекло наклеено'],
  },

  {
    key: 'iphone-14',
    title: 'iPhone 14 128GB',
    category: 'phones',
    basePrice: 46000,
    jitter: 0.18,
    weight: 2,
    desc: ['Аккум 89%, состояние как новое', 'Айклауд чистый, выход выполнен', 'Комплект полный, чек сохранён'],
  },
  {
    key: 'iphone-14-pro',
    title: 'iPhone 14 Pro 256GB',
    category: 'phones',
    basePrice: 68000,
    jitter: 0.15,
    weight: 1.5,
    desc: ['Дисплей без выгораний, остров живой', 'Камера без пыли, снимает как новый', 'Обмен не интересует, продажа только'],
  },
  {
    key: 'iphone-15',
    title: 'iPhone 15 128GB',
    category: 'phones',
    basePrice: 58000,
    jitter: 0.15,
    weight: 1.5,
    desc: ['Куплен в декабре, аккум 96%', 'Плёнка и чехол с первого дня', 'USB-C, зарядка в комплекте'],
  },
  {
    key: 'galaxy-s23',
    title: 'Samsung Galaxy S23 256GB',
    category: 'phones',
    basePrice: 42000,
    jitter: 0.18,
    weight: 1.5,
    desc: ['Флагман, всё бодро летает', 'Экран яркий, батарея держит день', 'Без ремонтов, гарантия ещё действует'],
  },
  {
    key: 'galaxy-s20-fe',
    title: 'Samsung Galaxy S20 FE 128GB',
    category: 'phones',
    basePrice: 12500,
    jitter: 0.25,
    desc: ['Амолед без выгораний, 120 Гц', 'Аккум 84%, хватает до вечера', 'Крышка с мелкими царапками, экран цел'],
  },
  {
    key: 'galaxy-a34',
    title: 'Samsung Galaxy A34 128GB',
    category: 'phones',
    basePrice: 9500,
    jitter: 0.2,
    weight: 2,
    desc: ['Батарея огромная, два дня держит', 'Без царапин, использовал аккуратно', 'NFC есть, оплата телефоном работает'],
  },
  {
    key: 'redmi-note-13',
    title: 'Xiaomi Redmi Note 13 256GB',
    category: 'phones',
    basePrice: 12000,
    jitter: 0.18,
    weight: 2.2,
    desc: ['Камера 108 Мп, снимает чётко', 'Быстрая зарядка, шнур родной', 'Полгода в использовании, как новый'],
  },
  {
    key: 'redmi-9',
    title: 'Xiaomi Redmi 9 64GB',
    category: 'phones',
    basePrice: 4500,
    jitter: 0.28,
    weight: 1.8,
    desc: ['Рабочая лошадка, всё исправно', 'Задняя крышка без трещин', 'Идеален как первый телефон ребёнку'],
  },
  {
    key: 'poco-f5',
    title: 'Poco F5 256GB',
    category: 'phones',
    basePrice: 17500,
    jitter: 0.2,
    desc: ['Проц игровой, танки на максималках', 'Амолед 120 Гц, без битых пикселей', 'Продаю из-за перехода на айфон'],
  },
  {
    key: 'realme-c55',
    title: 'Realme C55 128GB',
    category: 'phones',
    basePrice: 6500,
    jitter: 0.25,
    weight: 1.8,
    desc: ['Большой экран, заряда хватает на день', 'Задняя крышка чистая, без сколов', 'Отдам с чехлом и стеклом'],
  },
  {
    key: 'honor-90',
    title: 'Honor 90 256GB',
    category: 'phones',
    basePrice: 14500,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Камера топ для своей цены', 'Экран изогнутый, без царапин', 'Куплен в официальном магазине'],
  },
  {
    key: 'pixel-7',
    title: 'Google Pixel 7 128GB',
    category: 'phones',
    basePrice: 22000,
    jitter: 0.3,
    weight: 0.6,
    desc: ['Привезён из Европы, чистый андроид', 'Камера одна из лучших на рынке', 'Всё настроено, подходит энтузиастам'],
  },
  {
    key: 'tecno-spark-10',
    title: 'Tecno Spark 10 128GB',
    category: 'phones',
    basePrice: 5500,
    jitter: 0.28,
    weight: 1.8,
    desc: ['Недорогой, но всё шустро работает', 'Заряжается быстро, батарея свежая', 'Подарили второй, этот лишний'],
  },

  // ---------------- Ноутбуки ----------------
  {
    key: 'macbook-air-2020',
    title: 'MacBook Air 2020 (M1)',
    category: 'laptops',
    basePrice: 55000,
    jitter: 0.15,
    weight: 2,
    desc: [
      'Циклов заряда 210, аккум отличный',
      'Корпус без вмятин, клавиатура целая',
      'Коробка и зарядка в комплекте',
      'Отдаю дешевле рынка, деньги нужны',
    ],
  },
  {
    key: 'macbook-pro-2015',
    title: 'MacBook Pro 13" 2015',
    category: 'laptops',
    basePrice: 24000,
    jitter: 0.25,
    weight: 0.6,
    desc: ['Легенда, работает как часы', 'Аккум менял в прошлом году', 'Потёртости по корпусу, всё работает'],
  },
  {
    key: 'thinkpad-t480',
    title: 'ThinkPad T480 (i5, 16GB)',
    category: 'laptops',
    basePrice: 18000,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Служебный, ухоженный, клавиатура целая', 'Апгрейдится на раз: два слота памяти', 'Батарея держит четыре часа'],
  },
  {
    key: 'thinkpad-x1',
    title: 'ThinkPad X1 Carbon 7th gen',
    category: 'laptops',
    basePrice: 30000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Бизнес-класс, вес меньше килограмма', 'Карбоновый корпус, без трещин', 'Для работы идеально, всё летает'],
  },
  {
    key: 'asus-tuf-f15',
    title: 'ASUS TUF Gaming F15 (RTX 3060)',
    category: 'laptops',
    basePrice: 58000,
    jitter: 0.18,
    weight: 1.5,
    desc: ['Игровой, 144 Гц, видеокарта не душится', 'Чищен, термопаста свежая', 'Сумка и зарядка в комплекте'],
  },
  {
    key: 'acer-nitro-5',
    title: 'Acer Nitro 5 (GTX 1650)',
    category: 'laptops',
    basePrice: 44000,
    jitter: 0.2,
    weight: 1.6,
    desc: ['Тянет всё на высоких, проверено', 'Клава с подсветкой, шумит умеренно', 'Продаю, взял себе стационар'],
  },
  {
    key: 'msi-gf63',
    title: 'MSI GF63 Thin',
    category: 'laptops',
    basePrice: 46000,
    jitter: 0.2,
    weight: 0.8,
    desc: ['Тонкий игровой, для учёбы и игр хватит', 'Экран без битых пикселей', 'Небольшой люфт крышки, на работу не влияет'],
  },
  {
    key: 'hp-pavilion-15',
    title: 'HP Pavilion 15',
    category: 'laptops',
    basePrice: 24000,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Для учёбы и фильмов самое то', 'Аккум три часа спокойно', 'Мелкие царапки на крышке'],
  },
  {
    key: 'lenovo-ideapad-3',
    title: 'Lenovo IdeaPad 3',
    category: 'laptops',
    basePrice: 17500,
    jitter: 0.22,
    weight: 1.8,
    desc: ['Рабочая лошадка, ничего не лагает', 'Куплен для универа, диплом защищён', 'Комплект как из магазина'],
  },
  {
    key: 'dell-latitude-7490',
    title: 'Dell Latitude 7490',
    category: 'laptops',
    basePrice: 19500,
    jitter: 0.22,
    weight: 0.8,
    desc: ['Корпоративный, обслуженный', 'Аккум держит как новый', 'Металлический корпус, без люфтов'],
  },
  {
    key: 'huawei-matebook-d15',
    title: 'Huawei MateBook D15',
    category: 'laptops',
    basePrice: 28000,
    jitter: 0.2,
    desc: ['Экран красивый, рамки тонкие', 'Всё штатно, система чистая', 'Продаю из-за перехода на макбук'],
  },
  {
    key: 'asus-vivobook-15',
    title: 'ASUS VivoBook 15',
    category: 'laptops',
    basePrice: 21500,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Лёгкий, для учёбы идеален', 'Царапина на крышке, экран цел', 'Зарядное в комплекте'],
  },
  {
    key: 'macbook-air-2017',
    title: 'MacBook Air 13" 2017',
    category: 'laptops',
    basePrice: 17000,
    jitter: 0.25,
    weight: 0.8,
    desc: ['Рабочая лошадка для браузера и текстов', 'Аккум циклов 400, держит три часа', 'Пара вмятинок на углу, всё работает'],
  },

  {
    key: 'macbook-pro-14',
    title: 'MacBook Pro 14 M1 Pro 512GB',
    category: 'laptops',
    basePrice: 95000,
    jitter: 0.12,
    weight: 0.6,
    desc: ['Профессиональная машина, батарея держит день', 'Циклов заряда 130, состояние отличное', 'Продажа в связи с переходом на стационар'],
  },
  {
    key: 'macbook-air-m2',
    title: 'MacBook Air M2 8/256GB',
    category: 'laptops',
    basePrice: 75000,
    jitter: 0.12,
    weight: 0.7,
    desc: ['Тонкий, тихий, без вентиляторов', 'Аккум 94%, следы использования минимальные', 'Комплект: коробка, зарядка, кабель'],
  },
  {
    key: 'msi-katana-15',
    title: 'Ноутбук MSI Katana 15 RTX 4060',
    category: 'laptops',
    basePrice: 55000,
    jitter: 0.18,
    weight: 0.7,
    desc: ['Игровой, всё тянет на высоких', 'Охлаждение чистили, термопаста свежая', 'Клавиатура без залысин, подсветка работает'],
  },
  {
    key: 'hp-omen-15',
    title: 'Ноутбук HP Omen 15 RTX 3060',
    category: 'laptops',
    basePrice: 52000,
    jitter: 0.18,
    weight: 0.7,
    desc: ['Игровой монстр, экран 144 Гц', 'Батарея живая, но чаще от розетки', 'Причина продажи: собрал стационар'],
  },
  {
    key: 'asus-zenbook-14',
    title: 'Ноутбук ASUS Zenbook 14 OLED',
    category: 'laptops',
    basePrice: 45000,
    jitter: 0.18,
    weight: 0.7,
    desc: ['OLED экран, картинка космос', 'Вес килограмм с хвостиком, для работы идеален', 'Блок в комплекте, всё родное'],
  },
  {
    key: 'ideapad-gaming-3',
    title: 'Ноутбук Lenovo IdeaPad Gaming 3',
    category: 'laptops',
    basePrice: 38000,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Тянет танки и кс на средних', 'Оперативку докупил, стало 16 ГБ', 'Пара царапок на крышке, внутри чисто'],
  },
  {
    key: 'thinkpad-e14',
    title: 'Ноутбук Lenovo ThinkPad E14',
    category: 'laptops',
    basePrice: 32000,
    jitter: 0.2,
    desc: ['Рабочая лошадка для офиса', 'Клавиатура как новая, тачпад чистый', 'Аккум держит пять часов спокойно'],
  },
  {
    key: 'macbook-air-2019',
    title: 'MacBook Air 2019 8/128GB',
    category: 'laptops',
    basePrice: 28000,
    jitter: 0.2,
    desc: ['Для учёбы и браузера хватит с запасом', 'Аккум 80%, клавиатура работает чётко', 'Пара микроцарапок, в целом ухоженный'],
  },
  {
    key: 'honor-magicbook-15',
    title: 'Ноутбук Honor MagicBook 15',
    category: 'laptops',
    basePrice: 27000,
    jitter: 0.2,
    desc: ['Металлический корпус, выглядит дорого', 'Экран без рамок, картинка приятная', 'Отдам с чехлом, юзал для учёбы'],
  },
  {
    key: 'acer-aspire-5',
    title: 'Ноутбук Acer Aspire 5',
    category: 'laptops',
    basePrice: 25000,
    jitter: 0.22,
    weight: 1.5,
    desc: ['SSD поставил, летает бодро', 'Подходит для работы и сериалов', 'Кнопки все работают, ничего не гремит'],
  },
  {
    key: 'xiaomi-redmibook-15',
    title: 'Ноутбук Xiaomi RedmiBook 15',
    category: 'laptops',
    basePrice: 22000,
    jitter: 0.2,
    desc: ['Большой экран, для дома самое то', 'Кулер тихий, не греется', 'Продаю, взял себе макбук'],
  },
  {
    key: 'netbook-acer-one',
    title: 'Нетбук Acer Aspire One',
    category: 'laptops',
    basePrice: 6000,
    jitter: 0.3,
    weight: 0.6,
    desc: ['Маленький, для текстов и почты хватит', 'Система установлена, работает', 'Ностальгия, но пора освобождать полку'],
  },

  // ---------------- Системные блоки (стенд для апгрейдов) ----------------
  {
    key: 'pc-i5-build',
    title: 'Системный блок Intel i5-10400 / 16ГБ',
    category: 'electronics',
    basePrice: 28000,
    jitter: 0.22,
    weight: 0.9,
    desc: [
      'Сборка на LGA1200, оперативки 16ГБ DDR4',
      'Без видеокарты — графика в процессоре',
      'БП 500 Вт, корпус простой, но всё работает',
    ],
  },
  {
    key: 'pc-r5-build',
    title: 'Системный блок Ryzen 5 3600 / 16ГБ',
    category: 'electronics',
    basePrice: 30000,
    jitter: 0.22,
    weight: 0.9,
    desc: [
      'Платформа AM4, шесть ядер, DDR4 DIMM',
      'SSD на 512, корпус с сеткой',
      'Продам с апгрейдом под игры — нужен слот для видюхи',
    ],
  },

  // ---------------- Электроника ----------------
  {
    key: 'ps5',
    title: 'PlayStation 5 (с дисководом)',
    category: 'electronics',
    basePrice: 42000,
    jitter: 0.15,
    weight: 2.5,
    desc: [
      'Дисковод читает всё, вентилятор тихий',
      'Ухоженная, геймпад без люфта',
      'Шнур HDMI в комплекте',
      'Взял второй, это запасная',
    ],
  },
  {
    key: 'ps4-slim',
    title: 'PlayStation 4 Slim 500GB',
    category: 'electronics',
    basePrice: 13500,
    jitter: 0.2,
    weight: 2,
    desc: ['Читает диски, шумит в меру', 'Пять игр в подарок', 'Геймпад родной, стики без люфта'],
  },
  {
    key: 'xbox-series-s',
    title: 'Xbox Series S 512GB',
    category: 'electronics',
    basePrice: 19500,
    jitter: 0.2,
    desc: ['Компактная, всё работает', 'Геймпад целый, батарейки в подарок', 'Продаю, перешёл на плейстейшн'],
  },
  {
    key: 'nintendo-switch',
    title: 'Nintendo Switch',
    category: 'electronics',
    basePrice: 18000,
    jitter: 0.2,
    weight: 1.8,
    desc: ['Док, зарядка и чехол в комплекте', 'Джойсты не дрифтят, проверено', 'Экран под плёнкой с первого дня'],
  },
  {
    key: 'airpods-pro-2',
    title: 'AirPods Pro 2',
    category: 'electronics',
    basePrice: 12000,
    jitter: 0.18,
    weight: 2.2,
    desc: ['Оригинал, проверка по серийнику', 'Аккум держит как в день покупки', 'Кейс без сколов, амбушюры новые'],
  },
  {
    key: 'apple-watch-7',
    title: 'Apple Watch Series 7 45mm',
    category: 'electronics',
    basePrice: 15000,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Аккум день спокойно', 'Стекло целое, второй ремешок в подарок', 'Коробка и зарядка на месте'],
  },
  {
    key: 'galaxy-watch-4',
    title: 'Samsung Galaxy Watch4 44mm',
    category: 'electronics',
    basePrice: 7500,
    jitter: 0.25,
    weight: 0.8,
    desc: ['Состояние хорошее, стекло целое', 'Датчики работают, аккум норм', 'Два ремешка в подарок'],
  },
  {
    key: 'yandex-station-mini',
    title: 'Умная колонка Мини',
    category: 'electronics',
    basePrice: 4200,
    jitter: 0.2,
    weight: 2,
    desc: ['Работает идеально, звук приятный', 'Куплена лишняя, стоит без дела', 'Кабель в комплекте'],
  },
  {
    key: 'tv-samsung-43',
    title: 'Телевизор Samsung 43" 4K',
    category: 'electronics',
    basePrice: 26000,
    jitter: 0.2,
    weight: 1.6,
    desc: ['Матрица без битых пикселей', 'Пульт и ножки в комплекте', 'Висел в спальне, смотрели мало'],
  },
  {
    key: 'monitor-lg-24',
    title: 'Монитор LG 24" IPS 75Hz',
    category: 'electronics',
    basePrice: 7200,
    jitter: 0.22,
    weight: 1.6,
    desc: ['Битых пикселей нет, подсветка ровная', 'Для учёбы и работы идеален', 'Под кронштейн VESA'],
  },
  {
    key: 'sony-wh-1000xm4',
    title: 'Наушники Sony WH-1000XM4',
    category: 'electronics',
    basePrice: 14000,
    jitter: 0.2,
    desc: ['Шумодав работает как новый', 'Амбушюры целые, чехол в комплекте', 'Аккум держит сутки'],
  },
  {
    key: 'keychron-k2',
    title: 'Клавиатура Keychron K2',
    category: 'electronics',
    basePrice: 5800,
    jitter: 0.25,
    weight: 0.6,
    desc: ['Свитчи брауны, стук приятный', 'Все клавиши работают', 'Смотрится на столе отлично'],
  },

  {
    key: 'ps4-pro',
    title: 'PlayStation 4 Pro 1TB',
    category: 'electronics',
    basePrice: 18000,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Читает диски, вентилятор не шумит', 'Один геймпад, кабель HDMI в комплекте', 'Прошивка официальная, PSN работает'],
  },
  {
    key: 'xbox-one-s',
    title: 'Xbox One S 1TB',
    category: 'electronics',
    basePrice: 11000,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Тихая версия, не гудит', 'Геймпад без люфтов, стики целые', 'Подписка оформлена, чек покажу'],
  },
  {
    key: 'psp-3000',
    title: 'PSP 3000 с играми',
    category: 'electronics',
    basePrice: 5500,
    jitter: 0.3,
    weight: 0.7,
    desc: ['Экран яркий, без битых пикселей', 'Карта памяти на 32 ГБ, игр накидал', 'Ностальгия, но лежит без дела'],
  },
  {
    key: 'nintendo-switch-oled',
    title: 'Nintendo Switch OLED',
    category: 'electronics',
    basePrice: 28000,
    jitter: 0.18,
    desc: ['Экран OLED, цвета сочные', 'Док-станция и оба джойкона в комплекте', 'Дрейфа у джойконов нет, проверено'],
  },
  {
    key: 'airpods-2',
    title: 'AirPods 2',
    category: 'electronics',
    basePrice: 4500,
    jitter: 0.25,
    weight: 1.8,
    desc: ['Держат заряд около трёх часов', 'Подключаются к айфону мгновенно', 'Кейс родной, без сколов'],
  },
  {
    key: 'jbl-flip-5',
    title: 'Колонка JBL Flip 5',
    category: 'electronics',
    basePrice: 4200,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Басит прилично для своего размера', 'Защита от брызг, брал на дачу', 'Сетка без вмятин, кнопки работают'],
  },
  {
    key: 'tv-lg-55',
    title: 'Телевизор LG 55 дюймов 4K',
    category: 'electronics',
    basePrice: 28000,
    jitter: 0.2,
    desc: ['Матрица без засветов и битых пикселей', 'Смарт ТВ работает, пульт родной', 'Продаю из-за переезда, помогу спустить'],
  },
  {
    key: 'monitor-samsung-27',
    title: 'Монитор Samsung 27 дюймов IPS',
    category: 'electronics',
    basePrice: 14000,
    jitter: 0.2,
    desc: ['Ни одного битого пикселя', 'Ножка и кабель питания в комплекте', 'Идеален для работы с текстом'],
  },
  {
    key: 'marshall-stanmore',
    title: 'Колонка Marshall Stanmore 2',
    category: 'electronics',
    basePrice: 16000,
    jitter: 0.2,
    weight: 0.7,
    desc: ['Звук тёплый, ручки металлические', 'Bluetooth и AUX работают', 'Стояла на полке, царапин нет'],
  },
  {
    key: 'apple-watch-se',
    title: 'Apple Watch SE 44mm',
    category: 'electronics',
    basePrice: 12000,
    jitter: 0.2,
    desc: ['Аккум держит полтора дня', 'Ремешок сменён на новый', 'Пара потёртостей на корпусе, экран цел'],
  },
  {
    key: 'ipad-9',
    title: 'iPad 9 64GB Wi-Fi',
    category: 'electronics',
    basePrice: 19000,
    jitter: 0.18,
    desc: ['Как новый, в чехле с первого дня', 'Аккум отличный, заряжается быстро', 'Брал для учёбы, отдаю с чехлом-клавиатурой'],
  },
  {
    key: 'logitech-g502',
    title: 'Мышь Logitech G502 Hero',
    category: 'electronics',
    basePrice: 3000,
    jitter: 0.25,
    weight: 1.8,
    desc: ['Все кнопки работают, датчик чёткий', 'Грузики в комплекте, кабель цел', 'Легенда, но пересел на беспроводную'],
  },
  {
    key: 'rtx-3060',
    title: 'Видеокарта RTX 3060 12GB',
    category: 'electronics',
    basePrice: 18000,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Не майнилась, брал под игры', 'Температуры в норме, тесты покажу', 'Коробка и чек сохранены'],
  },
  {
    key: 'ddr4-16',
    title: 'Оперативная память DDR4 16GB (2x8)',
    category: 'electronics',
    basePrice: 2500,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Частота 3200, XMP включается', 'Работали в паре без ошибок', 'Апгрейднулся на 32, отдаю эти'],
  },
  {
    key: 'ssd-1tb',
    title: 'SSD 1TB Samsung 870 EVO',
    category: 'electronics',
    basePrice: 4800,
    jitter: 0.22,
    weight: 1.8,
    desc: ['Здоровье 98%, ресурс почти целый', 'Перезаписей немного, тесты покажу', 'Апгрейднулся на NVMe, этот лишний'],
  },
  {
    key: 'canon-600d',
    title: 'Фотоаппарат Canon 600D с китом',
    category: 'electronics',
    basePrice: 15000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Затвор отработал 12 тысяч кадров', 'Матрица чистая, объектив без пыли', 'Сумка и зарядка в комплекте'],
  },
  {
    key: 'gopro-hero-8',
    title: 'Экшн-камера GoPro Hero 8',
    category: 'electronics',
    basePrice: 13000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Снимала отпуска, стабилизация топ', 'Аккумулятор держит как новый', 'Крепления и зарядка в комплекте'],
  },

  // ---------------- Одежда ----------------
  {
    key: 'puhovik-uniqlo',
    title: 'Пуховик Uniqlo Ultra Light Down',
    category: 'clothes',
    basePrice: 3800,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Лёгкий, тёплый до минус двадцати', 'Носил один сезон, постиран', 'Размер M, на 48-50'],
  },
  {
    key: 'tnf-kurtka',
    title: 'Зимняя куртка The North Face',
    category: 'clothes',
    basePrice: 12000,
    jitter: 0.25,
    desc: ['Мембрана живая, капюшон цел', 'Оригинал, куплена в фирменном', 'Ношена пару сезонов, состояние супер'],
  },
  {
    key: 'levis-501',
    title: 'Джинсы Levi\'s 501',
    category: 'clothes',
    basePrice: 3400,
    jitter: 0.3,
    weight: 2,
    desc: ['Оригинал, строчка ровная', 'Посадка идеальная, размер 32', 'Носка минимальная, без потёртостей'],
  },
  {
    key: 'zara-hoodie',
    title: 'Худи Zara oversize',
    category: 'clothes',
    basePrice: 1700,
    jitter: 0.35,
    weight: 1.8,
    desc: ['Оверсайз, хлопок плотный', 'Одевала пару раз, как новое', 'Размер S, на рост 165'],
  },
  {
    key: 'massimo-palto',
    title: 'Пальто Massimo Dutti',
    category: 'clothes',
    basePrice: 6500,
    jitter: 0.28,
    weight: 0.8,
    desc: ['Шерсть, сидит идеально', 'Продаю, гардероб меняется', 'Химчистка сделана, носки почти нет'],
  },
  {
    key: 'henderson-kostyum',
    title: 'Костюм Henderson',
    category: 'clothes',
    basePrice: 8000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Одевал на встречи, состояние отличное', 'Подшит под рост 180, брюки 32', 'Чехол в подарок'],
  },
  {
    key: 'mango-dress',
    title: 'Платье Mango',
    category: 'clothes',
    basePrice: 1900,
    jitter: 0.35,
    weight: 1.5,
    desc: ['Лёгкое, для лета идеально', 'Одевала один раз на свадьбу', 'Размер XS-S'],
  },
  {
    key: 'carhartt-detroit',
    title: 'Куртка Carhartt WIP Detroit',
    category: 'clothes',
    basePrice: 9000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Канвас плотный, заломы красивые', 'Оригинал, покупал в профильном магазине', 'Сел идеально, но стиль сменился'],
  },
  {
    key: 'tommy-tishka',
    title: 'Футболка Tommy Hilfiger',
    category: 'clothes',
    basePrice: 1700,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Хлопок, не растянулась', 'Машинная стирка, принт целый', 'Размер L'],
  },
  {
    key: 'adidas-sportcost',
    title: 'Спортивный костюм Adidas',
    category: 'clothes',
    basePrice: 3400,
    jitter: 0.3,
    weight: 1.6,
    desc: ['Трикотаж живой, молния работает', 'Носил на пробежки, постиран', 'Размер L, на рост 180'],
  },
  {
    key: 'polushubok',
    title: 'Полушубок овчинный',
    category: 'clothes',
    basePrice: 8500,
    jitter: 0.3,
    weight: 0.5,
    desc: ['Овчина тёплая, молния новая', 'Хранился в чехле, без моли', 'Размер 50-52, забирайте до холодов'],
  },

  {
    key: 'zara-palto',
    title: 'Пальто Zara женское',
    category: 'clothes',
    basePrice: 6000,
    jitter: 0.3,
    desc: ['Размер S, носилось аккуратно', 'Шерсть с добавками, тёплое', 'Продаю, цвет не мой'],
  },
  {
    key: 'puhovik-zara',
    title: 'Пуховик Zara',
    category: 'clothes',
    basePrice: 7000,
    jitter: 0.25,
    desc: ['Размер M, тёплый, до минус 25 ходил', 'Все молнии работают, карманов полон', 'После чистки, выглядит прилично'],
  },
  {
    key: 'lacoste-polo',
    title: 'Поло Lacoste оригинал',
    category: 'clothes',
    basePrice: 3000,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Крокодил вышит, оригинал', 'Размер L, форма не потеряна', 'Носил аккуратно, без пятен'],
  },
  {
    key: 'dickies-kargo',
    title: 'Карго-брюки Dickies',
    category: 'clothes',
    basePrice: 3800,
    jitter: 0.3,
    desc: ['Размер 32, посадка классическая', 'Ткань плотная, карманов много', 'Один сезон носил, состояние хорошее'],
  },
  {
    key: 'wrangler-dzhinsy',
    title: 'Джинсы Wrangler',
    category: 'clothes',
    basePrice: 3200,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Прямые, размер 32/32', 'Без потёртостей и дырок', 'Мало носил, висели в шкафу'],
  },
  {
    key: 'uniqlo-merino',
    title: 'Свитер Uniqlo меринос',
    category: 'clothes',
    basePrice: 2200,
    jitter: 0.3,
    desc: ['Мериносовая шерсть, не колется', 'Размер M, катышков почти нет', 'Постиран и упакован'],
  },
  {
    key: 'kurtka-armeyskaya',
    title: 'Куртка демисезонная армейская',
    category: 'clothes',
    basePrice: 1800,
    jitter: 0.32,
    desc: ['Плотная, ветер не продувает', 'Размер 50-52, широкая', 'Отслужила своё, ещё послужит'],
  },
  {
    key: 'boss-rubashka',
    title: 'Рубашка Hugo Boss',
    category: 'clothes',
    basePrice: 4000,
    jitter: 0.3,
    desc: ['Оригинал, размер 48', 'Гладкая хлопковая ткань', 'Надевал пару раз на мероприятия'],
  },
  {
    key: 'palto-drap-vintage',
    title: 'Драповое пальто винтажное',
    category: 'clothes',
    basePrice: 2500,
    jitter: 0.35,
    weight: 0.7,
    desc: ['Советское, ткань плотная', 'Подкладка целая, пуговицы родные', 'Размер 48-50, смотрится стильно'],
  },
  {
    key: 'adidas-velur-kostyum',
    title: 'Спортивный костюм Adidas велюр',
    category: 'clothes',
    basePrice: 4500,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Велюровый, мягкий и приятный', 'Размер L, молнии целые', 'Три полоски родные, оригинал'],
  },
  {
    key: 'dublenka-kozhannaya',
    title: 'Дублёнка мужская кожаная',
    category: 'clothes',
    basePrice: 9000,
    jitter: 0.28,
    weight: 0.7,
    desc: ['Натуральная кожа, тёплая', 'Размер 52, воротник живой', 'Носил два сезона, храню в чехле'],
  },

  // ---------------- Кроссовки ----------------
  {
    key: 'nike-af1',
    title: 'Nike Air Force 1 \'07',
    category: 'sneakers',
    basePrice: 6000,
    jitter: 0.22,
    weight: 2.5,
    desc: ['Белые, отстирал до состояния новых', 'Подошва не отклеивается, всё цело', 'Размер 42 US 9, померить можно'],
  },
  {
    key: 'adidas-samba',
    title: 'Adidas Samba OG',
    category: 'sneakers',
    basePrice: 8000,
    jitter: 0.2,
    weight: 1.8,
    desc: ['Оригинал, коробка сохранилась', 'Замша целая, подошва чистая', 'Носил месяц всего'],
  },
  {
    key: 'nb-574',
    title: 'New Balance 574',
    category: 'sneakers',
    basePrice: 5300,
    jitter: 0.22,
    weight: 1.6,
    desc: ['Классика, сидят идеально', 'Стельки новые, носок лёгкий', 'Размер 43'],
  },
  {
    key: 'aj1-mid',
    title: 'Air Jordan 1 Mid',
    category: 'sneakers',
    basePrice: 11500,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Состояние близкое к идеалу', 'Коробка и чек есть', 'Носил только в сухую погоду'],
  },
  {
    key: 'asics-kayano-14',
    title: 'Asics Gel-Kayano 14',
    category: 'sneakers',
    basePrice: 8800,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Модель снова в моде, забирайте', 'Сетка целая, подошва не раскрошилась', 'Оригинал, размер 42.5'],
  },
  {
    key: 'puma-suede',
    title: 'Puma Suede Classic',
    category: 'sneakers',
    basePrice: 3400,
    jitter: 0.28,
    desc: ['Замша бархатная, без задиров', 'Ношены сезон, состояние хорошее', 'Размер 41'],
  },
  {
    key: 'reebok-classic',
    title: 'Reebok Classic Leather',
    category: 'sneakers',
    basePrice: 3300,
    jitter: 0.28,
    desc: ['Кожа мягкая, швы ровные', 'Классика на каждый день', 'Размер 44, маломерят на полразмера'],
  },
  {
    key: 'salomon-xt6',
    title: 'Salomon XT-6',
    category: 'sneakers',
    basePrice: 11000,
    jitter: 0.2,
    weight: 0.7,
    desc: ['Горная классика, состояние топ', 'Быстрая шнуровка работает чётко', 'Размер 43, оригинал'],
  },
  {
    key: 'vans-old-skool',
    title: 'Vans Old Skool',
    category: 'sneakers',
    basePrice: 3900,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Подошва держится крепко, ничего не отклеилось', 'Канвас без дырок, полосы целые', 'Размер 42'],
  },

  {
    key: 'nb-530',
    title: 'New Balance 530',
    category: 'sneakers',
    basePrice: 8000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Размер 43, сетка целая', 'Подошва почти не стёрта', 'Носил аккуратно, сезон один'],
  },
  {
    key: 'air-max-90',
    title: 'Nike Air Max 90',
    category: 'sneakers',
    basePrice: 9000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Классика, размер 42', 'Подушка держит воздух', 'Коробка сохранилась'],
  },
  {
    key: 'aj1-retro-high',
    title: 'Air Jordan 1 Retro High',
    category: 'sneakers',
    basePrice: 18000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Кожа без трещин, коробка родная', 'Размер 44, надевал пару раз', 'Чек из американского магазина'],
  },
  {
    key: 'yeezy-350',
    title: 'adidas Yeezy Boost 350 V2',
    category: 'sneakers',
    basePrice: 15000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Буст живой, мягко ходится', 'Размер 42, стельки родные', 'Оригинал, проверка при встрече'],
  },
  {
    key: 'adidas-gazelle',
    title: 'adidas Gazelle',
    category: 'sneakers',
    basePrice: 7000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Замша без залысин', 'Размер 43, подошва чистая', 'Носил под джинсы, выглядят отлично'],
  },
  {
    key: 'asics-gel-1130',
    title: 'ASICS Gel-1130',
    category: 'sneakers',
    basePrice: 7500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Гель работает, удобно бегать', 'Размер 44, без дырок', 'Один сезон, состояние хорошее'],
  },
  {
    key: 'converse-classic',
    title: 'Converse Chuck Taylor классика',
    category: 'sneakers',
    basePrice: 3500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Размер 41, ткань целая', 'Шнурки родные, швы целые', 'Классика, ещё отхаживают сезон'],
  },
  {
    key: 'dr-martens-1460',
    title: 'Dr. Martens 1460',
    category: 'sneakers',
    basePrice: 9500,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Кожа жёсткая, слегка разношены', 'Размер 43, подошва не стёрта', 'Жёлтая строчка родная, оригинал'],
  },
  {
    key: 'crocs-classic',
    title: 'Crocs классические',
    category: 'sneakers',
    basePrice: 2200,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Размер 43-44, без дырок лишних', 'Вымыты, готовы к сезону', 'Для дачи самое то'],
  },
  {
    key: 'skechers-dlx',
    title: 'Кроссовки Skechers',
    category: 'sneakers',
    basePrice: 3800,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Мемори-фоам, как тапочки', 'Размер 45, подошва живая', 'Ходить в них одно удовольствие'],
  },

  // ---------------- Мебель ----------------
  {
    key: 'divan-knizhka',
    title: 'Диван-книжка',
    category: 'furniture',
    basePrice: 5500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Механизм рабочий, спится отлично', 'Каркас крепкий, чехол постиран', 'Забрать до пятницы, освобождаю комнату'],
  },
  {
    key: 'friheten',
    title: 'Угловой диван IKEA Friheten',
    category: 'furniture',
    basePrice: 17500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Раскладывается, внутри ящик для белья', 'Чехол снимается и стирается', 'Служил три года, продаю из-за переезда'],
  },
  {
    key: 'bean-bag',
    title: 'Кресло-мешок',
    category: 'furniture',
    basePrice: 1800,
    jitter: 0.35,
    desc: ['Наполнитель не слежался', 'Чехол постиран, как новый', 'Отдам вместе с пуфом, если заберёте всё'],
  },
  {
    key: 'komod-sosna',
    title: 'Комод из массива сосны',
    category: 'furniture',
    basePrice: 4200,
    jitter: 0.3,
    desc: ['Массив, ящики ходят ровно', 'Небольшие следы использования', 'Подойдёт для дачи или детской'],
  },
  {
    key: 'komp-stol',
    title: 'Компьютерный стол',
    category: 'furniture',
    basePrice: 2400,
    jitter: 0.32,
    weight: 1.5,
    desc: ['Полка под клавиатуру выдвигается', 'Стабильный, не шатается', 'Разобрать помогу, крепёж цел'],
  },
  {
    key: 'shkaf-kupe',
    title: 'Шкаф-купе три двери',
    category: 'furniture',
    basePrice: 8500,
    jitter: 0.3,
    desc: ['Зеркала без сколов', 'Внутри штанга, полки и ящики', 'Разберём и вынесем сами'],
  },
  {
    key: 'krovat-160',
    title: 'Кровать 160х200 с основанием',
    category: 'furniture',
    basePrice: 7800,
    jitter: 0.3,
    desc: ['Основание ортопедическое, ламели целые', 'Матрас продам отдельно, если нужно', 'Каркас без сколов и трещин'],
  },
  {
    key: 'eames-kreslo',
    title: 'Кресло в стиле Eames',
    category: 'furniture',
    basePrice: 5200,
    jitter: 0.28,
    weight: 0.6,
    desc: ['Кожзам цел, ножки хромированные', 'Смотрится в интерьере дорого', 'Стилистика комнаты поменялась, продаю'],
  },
  {
    key: 'billy',
    title: 'Стеллаж IKEA Billy',
    category: 'furniture',
    basePrice: 2300,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Полки ровные, крепёж полный', 'Цвет белый, выцветания нет', 'Разобран, забирать удобно'],
  },

  {
    key: 'divan-uglovoy',
    title: 'Диван угловой с механизмом',
    category: 'furniture',
    basePrice: 25000,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Раскладывается в спальное место', 'Обивка без пятен, котов не было', 'Помогу разобрать и вынести'],
  },
  {
    key: 'kreslo-kozhannoe',
    title: 'Кресло кожаное офисное',
    category: 'furniture',
    basePrice: 18000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Натуральная кожа, без трещин', 'Крестовина стальная, газлифт держит', 'Куплен за 40, продаю дешевле'],
  },
  {
    key: 'krovat-180',
    title: 'Кровать двуспальная 180х200',
    category: 'furniture',
    basePrice: 14000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Каркас крепкий, основание с ламелями', 'Изголовье мягкое, обивка целая', 'Разбирается, вывезти несложно'],
  },
  {
    key: 'stenka-gostinaya',
    title: 'Стенка в гостиную',
    category: 'furniture',
    basePrice: 12000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Современная, без следов сборок-разборок', 'Шкафчики открываются мягко', 'Помогу вынести до лифта'],
  },
  {
    key: 'matras-ortoped',
    title: 'Матрас ортопедический 160х200',
    category: 'furniture',
    basePrice: 9000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Пружинный, жёсткость средняя', 'Проветрен, чехол постиран', 'Пользовались два года, не проседает'],
  },
  {
    key: 'komod-malm',
    title: 'Комод IKEA Malm',
    category: 'furniture',
    basePrice: 8500,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Четыре ящика, направляющие тихие', 'Цвет белый, без сколов', 'Собран, но разберётся любой'],
  },
  {
    key: 'kuhonnyy-ugolok',
    title: 'Кухонный уголок с диванчиком',
    category: 'furniture',
    basePrice: 8000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Ящики под сиденьем работают', 'Обивка вымыта, без порезов', 'Причина продажи: новая кухня'],
  },
  {
    key: 'stol-raskladnoy',
    title: 'Стол обеденный раскладной',
    category: 'furniture',
    basePrice: 7000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Раскрывается до шести человек', 'Столешница без глубоких царапин', 'Механизм работает чётко'],
  },
  {
    key: 'stulya-4',
    title: 'Стулья обеденные, 4 шт',
    category: 'furniture',
    basePrice: 5000,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Не шатаются, сиденья целые', 'Обивка без пятен', 'Продаю пачкой, по отдельности дороже'],
  },
  {
    key: 'stenka-sovetskaya',
    title: 'Стенка советская полированная',
    category: 'furniture',
    basePrice: 3500,
    jitter: 0.35,
    weight: 0.7,
    desc: ['Полированная, дедушкина', 'Ящики все ходят, ключи есть', 'На дачу или винтажным любителям'],
  },
  {
    key: 'zerkalo-nastennoe',
    title: 'Зеркало настенное в раме',
    category: 'furniture',
    basePrice: 2000,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Стекло без пятен и сколов', 'Рама деревянная, крепёж есть', 'Осталось от ремонта, не подошло'],
  },

  // ---------------- Бытовая техника ----------------
  {
    key: 'robot-xiaomi',
    title: 'Робот-пылесос Xiaomi',
    category: 'appliances',
    basePrice: 9000,
    jitter: 0.2,
    weight: 2,
    desc: ['Датчики чистые, ездит по плану', 'Аккум убирает три комнаты', 'Контейнер и щётки в комплекте'],
  },
  {
    key: 'atlant-holodilnik',
    title: 'Холодильник Атлант двухкамерный',
    category: 'appliances',
    basePrice: 12000,
    jitter: 0.25,
    desc: ['Морозит отлично, морозилка держит лёд', 'Куплен пять лет назад, обслужен', 'Дверцы перевешиваются, зазоры ровные'],
  },
  {
    key: 'lg-stiralka',
    title: 'Стиральная машина LG 6 кг',
    category: 'appliances',
    basePrice: 10500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Прямой привод, шумит мало', 'ТЭН рабочий, стирала регулярно', 'Заливной шланг в комплекте'],
  },
  {
    key: 'svch-samsung',
    title: 'Микроволновка Samsung 23 л',
    category: 'appliances',
    basePrice: 2900,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Греет ровно, дверца прилегает', 'Эмаль внутри целая', 'Стояла на даче, включали пару раз'],
  },
  {
    key: 'multivarka-redmond',
    title: 'Мультиварка Redmond',
    category: 'appliances',
    basePrice: 2400,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Чаша без царапин, клапан целый', 'Книжку рецептов приложу', 'Продаю из-за переезда'],
  },
  {
    key: 'dyson-v8',
    title: 'Пылесос Dyson V8',
    category: 'appliances',
    basePrice: 12000,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Аккум живой, тянет двадцать минут в турбо', 'Фильтр промыт, насадки все', 'Настенный док в подарок'],
  },
  {
    key: 'delonghi-kofemashina',
    title: 'Кофемашина DeLonghi',
    category: 'appliances',
    basePrice: 14500,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Капучинатор работает, накипи нет', 'Чищена по инструкции', 'Готовит эспрессо как в кофейне'],
  },
  {
    key: 'bosch-duhovka',
    title: 'Духовка Bosch встраиваемая',
    category: 'appliances',
    basePrice: 8500,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Нагрев ровный, конвекция работает', 'Стекло без трещин, решётки целые', 'Снимается при замене кухни'],
  },
  {
    key: 'noirot-konvektor',
    title: 'Конвектор Noirot 1000 Вт',
    category: 'appliances',
    basePrice: 2900,
    jitter: 0.3,
    weight: 0.8,
    desc: ['Греет быстро, терморегулятор точный', 'Один сезон работы', 'Кабель целый, крепления на стену есть'],
  },

  {
    key: 'holodilnik-indesit',
    title: 'Холодильник Indesit двухкамерный',
    category: 'appliances',
    basePrice: 15000,
    jitter: 0.22,
    weight: 1.5,
    desc: ['Морозит отлично, не шумит', 'Полки все, уплотнители целые', 'Продаю в связи с переездом'],
  },
  {
    key: 'stiralka-bosch',
    title: 'Стиральная машина Bosch 6 кг',
    category: 'appliances',
    basePrice: 18000,
    jitter: 0.2,
    weight: 1.5,
    desc: ['Отжимает тихо, подшипники целы', 'Тэн чистый, накипи нет', 'Отработала пять лет без ремонтов'],
  },
  {
    key: 'posudomoyka-bosch',
    title: 'Посудомоечная машина Bosch',
    category: 'appliances',
    basePrice: 20000,
    jitter: 0.2,
    weight: 0.8,
    desc: ['Моет до блеска, все режимы работают', 'Корзины целые, без ржавчины', 'Отдаю, кухня не позволила оставить'],
  },
  {
    key: 'konditsioner-09',
    title: 'Кондиционер 9 (27 м2)',
    category: 'appliances',
    basePrice: 22000,
    jitter: 0.22,
    weight: 0.8,
    desc: ['Холодит и греет, пульт в комплекте', 'Снят аккуратно, фреон закачан', 'Установку обсудим, есть мастера'],
  },
  {
    key: 'plita-gefest',
    title: 'Плита газовая Gefest',
    category: 'appliances',
    basePrice: 6000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Все конфорки работают, электроподжиг живой', 'Духовка печёт ровно', 'Решётки чугунные, без сколов'],
  },
  {
    key: 'vodonagrevatel-80',
    title: 'Водонагреватель 80 литров',
    category: 'appliances',
    basePrice: 8000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Тэн менялся в прошлом году', 'Бак цел, не течёт', 'Отдаю из-за установки газа'],
  },
  {
    key: 'shveynaya-janome',
    title: 'Швейная машина Janome',
    category: 'appliances',
    basePrice: 8000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Шьёт ровно, челнок работает', 'Ножная педаль и чехол в комплекте', 'Мама шила на ней лет десять'],
  },
  {
    key: 'pylesos-samsung',
    title: 'Пылесос Samsung 1800 Вт',
    category: 'appliances',
    basePrice: 4500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Тянет хорошо, фильтр новый', 'Насадки все, шланг без трещин', 'Купили робот, этот не нужен'],
  },
  {
    key: 'miasorubka-electro',
    title: 'Мясорубка электрическая',
    category: 'appliances',
    basePrice: 3500,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Мотор мощный, мясо крутит легко', 'Ножи и решётки в комплекте', 'Нужна была на праздники, теперь простаивает'],
  },
  {
    key: 'utyug-philips',
    title: 'Утюг Philips с отпариванием',
    category: 'appliances',
    basePrice: 1800,
    jitter: 0.3,
    weight: 1.8,
    desc: ['Парит бодро, подошва чистая', 'Накипь очищалась регулярно', 'Подарили парогенератор, этот лишний'],
  },
  {
    key: 'chaynik-electro',
    title: 'Чайник электрический стеклянный',
    category: 'appliances',
    basePrice: 1200,
    jitter: 0.3,
    weight: 2,
    desc: ['Кипятит быстро, подсветка работает', 'Накипи почти нет', 'Подарили второй, отдаю этот'],
  },
  {
    key: 'blender-braun',
    title: 'Блендер Braun погружной',
    category: 'appliances',
    basePrice: 2200,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Мотор бодрый, супы делает за минуту', 'Чаша и венчик в комплекте', 'Пользуюсь редко, лежит без дела'],
  },

  // ---------------- Хобби и отдых ----------------
  {
    key: 'xiaomi-m365',
    title: 'Электросамокат Xiaomi M365',
    category: 'hobby',
    basePrice: 11500,
    jitter: 0.22,
    weight: 1.8,
    desc: ['Пробег небольшой, ездил по вечерам', 'Аккум живой, тормоза настроены', 'Камеры менял в прошлом сезоне'],
  },
  {
    key: 'stels-navigator',
    title: 'Велосипед Stels Navigator',
    category: 'hobby',
    basePrice: 7500,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Переключается ровно, тормоза новые', 'Катался два сезона, хранился в гараже', 'Крылья и багажник в комплекте'],
  },
  {
    key: 'karkasson',
    title: 'Настольная игра Каркассон',
    category: 'hobby',
    basePrice: 1400,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Все фишки и карточки на месте', 'Коробка целая, правила есть', 'Играли всей семьёй, отходим от настолок'],
  },
  {
    key: 'palatka-3',
    title: 'Палатка 3-местная',
    category: 'hobby',
    basePrice: 3300,
    jitter: 0.3,
    desc: ['Дождь держала, проверено', 'Швы проклеены, дуги целые', 'Ходили в неё дважды'],
  },
  {
    key: 'aquarium-60',
    title: 'Аквариум 60 л с тумбой',
    category: 'hobby',
    basePrice: 2800,
    jitter: 0.35,
    weight: 0.5,
    desc: ['Стёкла без сколов, швы герметичны', 'Фильтр и лампа в подарок', 'Рыб раздал, продаю пустым'],
  },
  {
    key: 'dualshock-4',
    title: 'Геймпад DualShock 4',
    category: 'hobby',
    basePrice: 2400,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Стики без люфта, отзыв живой', 'Аккум держит как новый', 'Шнур зарядки в комплекте'],
  },
  {
    key: 'garmin-etrex',
    title: 'Навигатор Garmin eTrex',
    category: 'hobby',
    basePrice: 4800,
    jitter: 0.3,
    weight: 0.4,
    desc: ['Спутники ловит быстро, корпус целый', 'Работает от батареек АА', 'Карта России загружена'],
  },
  {
    key: 'teleskop-skywatcher',
    title: 'Телескоп Sky-Watcher 707',
    category: 'hobby',
    basePrice: 8500,
    jitter: 0.3,
    weight: 0.4,
    desc: ['Оптика чистая, без царапин', 'Штатив устойчивый, всё в комплекте', 'Смотрели Луну и Сатурн, кольца видно'],
  },
  {
    key: 'metalloiskatel-xterra',
    title: 'Металлоискатель X-Terra 305',
    category: 'hobby',
    basePrice: 16000,
    jitter: 0.3,
    weight: 0.4,
    desc: ['Катушка штатная, дискриминация работает', 'Выходил с ним каждые выходные', 'Батарейный отсек сухой, коррозии нет'],
  },

  {
    key: 'gt-aggressor',
    title: 'Велосипед GT Aggressor 26',
    category: 'hobby',
    basePrice: 22000,
    jitter: 0.2,
    weight: 0.7,
    desc: ['Хардтейл, обкатан, всё настроено', 'Цепь и тормоза менялись недавно', 'Катался пару сезонов, рама без вмятин'],
  },
  {
    key: 'kugoo-m4',
    title: 'Электросамокат Kugoo M4 Pro',
    category: 'hobby',
    basePrice: 18000,
    jitter: 0.22,
    weight: 0.8,
    desc: ['Пробег небольшой, батарея держит', 'Складной, в лифт заходит спокойно', 'Багажник и сиденье в комплекте'],
  },
  {
    key: 'oculus-quest-2',
    title: 'Шлем виртуальной реальности Quest 2',
    category: 'hobby',
    basePrice: 14000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Линзы чистые, накладка целая', 'Игр накачано прилично', 'Продаю, глаза утомляет'],
  },
  {
    key: 'elektrovelosiped',
    title: 'Электровелосипед 500 Вт',
    category: 'hobby',
    basePrice: 35000,
    jitter: 0.22,
    weight: 0.6,
    desc: ['Ходит до 40 км на заряде', 'Батарея снимается, зарядка в комплекте', 'Ездил по выходным, хранится в гараже'],
  },
  {
    key: 'gyroskuter',
    title: 'Гироскутер 6.5 дюйма',
    category: 'hobby',
    basePrice: 7000,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Колёса целые, подсветка работает', 'Держит заряд около часа езды', 'Ребёнок вырос, пылится в прихожей'],
  },
  {
    key: 'drel-makita',
    title: 'Шуруповёрт Makita с двумя АКБ',
    category: 'hobby',
    basePrice: 5000,
    jitter: 0.25,
    weight: 1.8,
    desc: ['Крутит уверенно, трещотка работает', 'Обе батареи держат заряд', 'Чемодан и зарядка в комплекте'],
  },
  {
    key: 'nabor-instrumentov',
    title: 'Набор инструментов 108 предметов',
    category: 'hobby',
    basePrice: 4000,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Головки и ключи все на месте', 'Кейс закрывается, лотки целые', 'Дубликат, подарили второй'],
  },
  {
    key: 'xbox-geympad',
    title: 'Геймпад Xbox Series',
    category: 'hobby',
    basePrice: 3500,
    jitter: 0.25,
    weight: 1.8,
    desc: ['Стики не задраны, всё отзывчивое', 'Работает и по проводу, и по Bluetooth', 'Второй пад, играем в одиночку'],
  },
  {
    key: 'spinning-set',
    title: 'Спиннинг с катушкой',
    category: 'hobby',
    basePrice: 3000,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Тест до 20 г, кольца целые', 'Катушка без люфтов, леска новая', 'Брал на сезон, цена ниже магазина'],
  },
  {
    key: 'shahmaty-sovetskie',
    title: 'Шахматы советские деревянные',
    category: 'hobby',
    basePrice: 2500,
    jitter: 0.3,
    weight: 0.7,
    desc: ['Дерево, фигуры утяжелённые', 'Доска без трещин, складывается', 'Достались от деда, играют отлично'],
  },
  {
    key: 'mngal',
    title: 'Мангал складной',
    category: 'hobby',
    basePrice: 2500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Сталь толстая, не повело', 'Складывается, в багажник влезает', 'Дача продана, отдаю дешевле'],
  },
  {
    key: 'igra-ps4-5',
    title: 'Игры PS4, 5 дисков',
    category: 'hobby',
    basePrice: 2500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['ФИФА, ГТА и ещё три диска', 'Все читаются, коробки целые', 'Отдам пачкой, торг при встрече'],
  },
  {
    key: 'binokl-bpc',
    title: 'Бинокль БПЦ 8х30',
    category: 'hobby',
    basePrice: 2200,
    jitter: 0.3,
    weight: 0.7,
    desc: ['Советский, картинка чёткая', 'Юстировка в норме, без грибка', 'Чехол родной, ремень на месте'],
  },

  // ---------------- Спорт ----------------
  {
    key: 'ganteli-16',
    title: 'Гантели разборные 2х16 кг',
    category: 'sport',
    basePrice: 3400,
    jitter: 0.28,
    weight: 1.6,
    desc: ['Блины сидят плотно, гайки целые', 'Ручки обрезинены, руки не натирают', 'Забирай, места в квартире нет'],
  },
  {
    key: 'shtanga-50',
    title: 'Штанга с блинами 50 кг',
    category: 'sport',
    basePrice: 4800,
    jitter: 0.28,
    desc: ['Гриф ровный, блины чугунные', 'Замки-защёлки в комплекте', 'Отдам вместе с лямками'],
  },
  {
    key: 'begovaya-dorozhka',
    title: 'Беговая дорожка электрическая',
    category: 'sport',
    basePrice: 14500,
    jitter: 0.25,
    desc: ['Складывается, мотор не шумит', 'Полотно не проскальзывает', 'Пробег небольшой, смотрится прилично'],
  },
  {
    key: 'velotrenazher',
    title: 'Велотренажёр магнитный',
    category: 'sport',
    basePrice: 7500,
    jitter: 0.28,
    desc: ['Восемь уровней нагрузки', 'Сиденье регулируется, педали целые', 'Стояла без дела, отдаю дешевле'],
  },
  {
    key: 'burton-custom',
    title: 'Сноуборд Burton Custom 158',
    category: 'sport',
    basePrice: 14000,
    jitter: 0.25,
    weight: 0.5,
    desc: ['Кант цел, скользяк без глубоких царапин', 'Крепления отдам в подарок', 'Доска живая, проверена в горах'],
  },
  {
    key: 'bauer-konki',
    title: 'Коньки хоккейные Bauer',
    category: 'sport',
    basePrice: 3800,
    jitter: 0.3,
    weight: 0.8,
    desc: ['Лезвия затачены, ботинок держит голеностоп', 'Размер 43, шнуровка новая', 'Ходили два сезона в коробку'],
  },
  {
    key: 'rollerblade',
    title: 'Ролики Rollerblade',
    category: 'sport',
    basePrice: 3300,
    jitter: 0.3,
    desc: ['Колёса 80 мм, подшипники живые', 'Тормоз на месте, рама ровная', 'Размер 42-43'],
  },
  {
    key: 'wilson-raketki',
    title: 'Теннисные ракетки Wilson (2 шт)',
    category: 'sport',
    basePrice: 3800,
    jitter: 0.3,
    weight: 0.5,
    desc: ['Струны свежие, обмотка целая', 'Чехлы в комплекте', 'Брал для пары игр на корте, дальше пылятся'],
  },
  {
    key: 'turnik',
    title: 'Турник настенный',
    category: 'sport',
    basePrice: 1400,
    jitter: 0.32,
    weight: 1.5,
    desc: ['Держит сто двадцать, проверено мной', 'Порошковая покраска, без ржавчины', 'Крепёж полный, анкеры в комплекте'],
  },

  {
    key: 'ellipticheskiy-trenazher',
    title: 'Эллиптический тренажёр',
    category: 'sport',
    basePrice: 14000,
    jitter: 0.22,
    weight: 0.8,
    desc: ['Ход плавный, всё работает', 'Компьютер показывает время и пульс', 'Разберём при вывозе, самовывоз'],
  },
  {
    key: 'sap-doska',
    title: 'SAP-доска надувная',
    category: 'sport',
    basePrice: 18000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Комплект: насос, весло, чехол', 'Проколов нет, воздух держит', 'Два сезона на воде, состояние хорошее'],
  },
  {
    key: 'lyzhi-fischer',
    title: 'Беговые лыжи Fischer 190 с ботинками',
    category: 'sport',
    basePrice: 12000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Скользячка без царапин, камень не встречал', 'Крепления SNS, ботинки 43 в комплекте', 'Хранились в квартире, вертикально'],
  },
  {
    key: 'ganteli-razbornye',
    title: 'Гантели разборные 2 по 24 кг',
    category: 'sport',
    basePrice: 8000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Блины обрезиненные, замки затягиваются', 'Грифы ровные, без ржавчины', 'Кладовка освобождается, забирайте'],
  },
  {
    key: 'tennis-stol',
    title: 'Стол для настольного тенниса',
    category: 'sport',
    basePrice: 9000,
    jitter: 0.25,
    weight: 0.8,
    desc: ['Покрытие без пузырей, сетка целая', 'Складной, на колёсиках', 'Ракетки и мячи отдаю в подарок'],
  },
  {
    key: 'skameya-zhim',
    title: 'Скамья для жима со стойками',
    category: 'sport',
    basePrice: 5000,
    jitter: 0.28,
    desc: ['Стойки регулируются, болты затянуты', 'Обивка целая, каркас крепкий', 'Переехал, некуда поставить'],
  },
  {
    key: 'ryukzak-turisticheskiy',
    title: 'Рюкзак туристический 80 л',
    category: 'sport',
    basePrice: 4500,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Каркас живой, дождевик в комплекте', 'Молнии все работают', 'Сходил один поход, хватит с меня'],
  },
  {
    key: 'boxing-grusha',
    title: 'Груша боксёрская с перчатками',
    category: 'sport',
    basePrice: 3500,
    jitter: 0.3,
    desc: ['Кожа потёртая, но швы целые', 'Перчатки почти новые, размер L', 'Крепление в потолок есть'],
  },
  {
    key: 'skeytbord',
    title: 'Скейтборд уличный',
    category: 'sport',
    basePrice: 3500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Подвески настроены, деку не ломал', 'Колёса катятся ровно', 'Учился стоять, дальше не пошло'],
  },
  {
    key: 'kimono-dzyudo',
    title: 'Кимоно для дзюдо',
    category: 'sport',
    basePrice: 2500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Плотная ткань, размер 170', 'Пояс в комплекте', 'Сын бросил секцию, кимоно ждёт'],
  },
  {
    key: 'veloshlem',
    title: 'Велошлем с регулировкой',
    category: 'sport',
    basePrice: 1500,
    jitter: 0.32,
    weight: 1.8,
    desc: ['Без падений, трещин нет', 'Размер универсальный, 54-58', 'Прокладки целые, вымыт'],
  },
  {
    key: 'myach-futbolnyy',
    title: 'Мяч футбольный №5',
    category: 'sport',
    basePrice: 800,
    jitter: 0.32,
    weight: 2,
    desc: ['Держит воздух, ниппель целый', 'Сшит хорошо, не лохматится', 'Играли во дворе пару недель'],
  },

  // ---------------- Музыка ----------------
  {
    key: 'fender-strat-mex',
    title: 'Fender Stratocaster (Мексика)',
    category: 'music',
    basePrice: 33000,
    jitter: 0.2,
    weight: 0.7,
    desc: ['Звук живой, электроника родная', 'Гриф ровный, строит по всей длине', 'Кейс в подарок'],
  },
  {
    key: 'yamaha-f310',
    title: 'Гитара Yamaha F310',
    category: 'music',
    basePrice: 6500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Лучшая гитара для старта', 'Струны новые, гриф ровный', 'Звук громкий и тёплый'],
  },
  {
    key: 'yamaha-psr-e373',
    title: 'Синтезатор Yamaha PSR-E373',
    category: 'music',
    basePrice: 13500,
    jitter: 0.22,
    desc: ['Клавиши полувзвешенные, всё отзывчивое', 'Куча тембров и автоаккомпанемент', 'Адаптер в комплекте, стенд отдельно'],
  },
  {
    key: 'at-lp60x',
    title: 'Проигрыватель Audio-Technica LP60X',
    category: 'music',
    basePrice: 8800,
    jitter: 0.22,
    weight: 0.8,
    desc: ['Полностью автомат, иглу менял недавно', 'Крутит ровно, фон минимальный', 'Лучший старт для винильщика'],
  },
  {
    key: 'vinil-20',
    title: 'Виниловые пластинки (20 шт)',
    category: 'music',
    basePrice: 3800,
    jitter: 0.35,
    weight: 0.7,
    desc: ['Состояние от хорошего до отличного', 'Рок и поп, список пришлю', 'Отдам всё сразу, по одной не разбирать'],
  },
  {
    key: 'squier-strat',
    title: 'Электрогитара Squier Strat',
    category: 'music',
    basePrice: 9500,
    jitter: 0.22,
    desc: ['Для учёбы идеальна, звук ровный', 'Ручки не хрустят, розетка родная', 'Ремешок и медиаторы в подарок'],
  },
  {
    key: 'fender-champion-20',
    title: 'Комбоусилитель Fender Champion 20',
    category: 'music',
    basePrice: 7800,
    jitter: 0.25,
    weight: 0.6,
    desc: ['Двенадцать эффектов, чистый звук приятный', 'Громкости хватает на комнату и гараж', 'Работал без нареканий'],
  },
  {
    key: 'ukulele',
    title: 'Укулеле concert',
    category: 'music',
    basePrice: 1900,
    jitter: 0.3,
    weight: 0.7,
    desc: ['Нейлон мягкий, пальцам комфортно', 'Строй держит, колки не проскальзывают', 'Чехол в подарок, брал для поездок'],
  },

  {
    key: 'epiphone-les-paul',
    title: 'Электрогитара Epiphone Les Paul 100',
    category: 'music',
    basePrice: 35000,
    jitter: 0.2,
    weight: 0.6,
    desc: ['Звук плотный, сустейн на месте', 'Лады целые, гриф не ведён', 'Чехол жёсткий в подарок'],
  },
  {
    key: 'barabannaya-ustanovka',
    title: 'Барабанная установка 5 барабанов',
    category: 'music',
    basePrice: 25000,
    jitter: 0.22,
    weight: 0.6,
    desc: ['Обода ровные, пластики новые', 'Тарелки и стойки в комплекте', 'Соседи выставили условие, продаю'],
  },
  {
    key: 'bass-squier',
    title: 'Бас-гитара Squier Affinity',
    category: 'music',
    basePrice: 16000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Звук ровный, ручки не трещат', 'Струны новые, гриф удобный', 'Играл дома, соседей не жалел'],
  },
  {
    key: 'casio-ctk-3200',
    title: 'Синтезатор Casio CTK-3200',
    category: 'music',
    basePrice: 8000,
    jitter: 0.25,
    weight: 0.8,
    desc: ['61 клавиша, все работают', 'Питание и пюпитр в комплекте', 'Дочка бросила музыкальную школу'],
  },
  {
    key: 'shure-sm58',
    title: 'Микрофон Shure SM58',
    category: 'music',
    basePrice: 8000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Легенда вокала, капсюль целый', 'Гриль без вмятин, провод новый', 'Кабель XLR в подарок'],
  },
  {
    key: 'skripka',
    title: 'Скрипка 4/4 с смычком',
    category: 'music',
    basePrice: 7000,
    jitter: 0.28,
    weight: 0.6,
    desc: ['Лак родной, трещин нет', 'Смычок и канифоль в кейсе', 'Настраивается, звучит приятно'],
  },
  {
    key: 'zoom-multieffekt',
    title: 'Мультиэффект Zoom G1X Four',
    category: 'music',
    basePrice: 6000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Все пресеты работают, педаль живая', 'Блок питания в комплекте', 'Перешёл на процессор в стойке'],
  },
  {
    key: 'klassicheskaya-gitara',
    title: 'Гитара классическая 6 струн',
    category: 'music',
    basePrice: 4500,
    jitter: 0.28,
    weight: 1.8,
    desc: ['Нейлон, для обучения самое то', 'Строй держит, гриф ровный', 'Играл в универе, теперь пылится'],
  },
  {
    key: 'balalayka',
    title: 'Балалайка трёхструнная',
    category: 'music',
    basePrice: 3000,
    jitter: 0.32,
    weight: 0.6,
    desc: ['Советская, звук звонкий', 'Струны новые, медиатор в подарок', 'На праздниках заходит на ура'],
  },
  {
    key: 'hohner-garmonika',
    title: 'Губная гармошка Hohner',
    category: 'music',
    basePrice: 2000,
    jitter: 0.3,
    weight: 0.7,
    desc: ['Ключ до, все клапаны работают', 'Не заедает, дышится легко', 'Освоил несколько мелодий, продаю'],
  },

  // ---------------- Авто и мото ----------------
  {
    key: 'nokian-8',
    title: 'Шины Nokian Hakkapeliitta 8 (4 шт)',
    category: 'auto',
    basePrice: 17000,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Шипы почти все на месте, протектор 7 мм', 'Хранились в сухом гараже', 'Продаю в связи со сменой машины'],
  },
  {
    key: 'advocam',
    title: 'Видеорегистратор AdvoCam FD7',
    category: 'auto',
    basePrice: 3200,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Пишет чётко и днём и ночью', 'Крепление на присоске, кабель есть', 'Снял с проданной машины'],
  },
  {
    key: 'pioneer-2din',
    title: 'Магнитола Pioneer 2DIN',
    category: 'auto',
    basePrice: 5800,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Экран живой, сенсор отзывчивый', 'Bluetooth работает, микрофон в комплекте', 'Подходит на большинство иномарок'],
  },
  {
    key: 'domkrat-2t',
    title: 'Домкрат подкатной 2т',
    category: 'auto',
    basePrice: 1300,
    jitter: 0.3,
    desc: ['Поднимает уверенно, клапан не травит', 'Масло не подтекает', 'Лежал в багажнике, рабочее состояние'],
  },
  {
    key: 'poperechniny',
    title: 'Поперечины на крышу',
    category: 'auto',
    basePrice: 3800,
    jitter: 0.3,
    weight: 0.6,
    desc: ['Сталь, замки целые', 'Подходили на Kia Ceed', 'Ключи в комплекте'],
  },
  {
    key: 'avtokompressor',
    title: 'Автомобильный компрессор',
    category: 'auto',
    basePrice: 1500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Накачивает колесо за три минуты', 'Шланг и насадки на месте', 'Проверен перед продажей'],
  },
  {
    key: 'diski-r16',
    title: 'Литые диски R16 (4 шт)',
    category: 'auto',
    basePrice: 7800,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Балансировка нормальная, кривых нет', 'Подходили на Ford Focus', 'Покрышки не продаю, только диски'],
  },
  {
    key: 'hjc-shlem',
    title: 'Мотошлем HJC',
    category: 'auto',
    basePrice: 4800,
    jitter: 0.28,
    weight: 0.6,
    desc: ['Стекло без царапин, подкладка целая', 'Размер L, застёжка работает', 'Не падал, куплен в мотосалоне'],
  },

  {
    key: 'snezhohod-buran',
    title: 'Снегоход Буран',
    category: 'auto',
    basePrice: 150000,
    jitter: 0.2,
    weight: 0.5,
    desc: ['Мотор ровный, ходовая обслужена', 'Капот и сиденье целые, лыжи новые', 'Документы в порядке, готов к сезону'],
  },
  {
    key: 'motocikl-izh-5',
    title: 'Мотоцикл ИЖ Планета 5',
    category: 'auto',
    basePrice: 55000,
    jitter: 0.25,
    weight: 0.6,
    desc: ['Заводится с пол-тычка, коробка чёткая', 'Колёса новые, цепь свежая', 'Документы на руках, ездил до осени'],
  },
  {
    key: 'moped-alfa',
    title: 'Мопед Альфа 110',
    category: 'auto',
    basePrice: 45000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Пробег небольшой, едет 70 км/ч', 'Электростартер работает, кик-стартер на месте', 'Куплен сыну, вырос из него'],
  },
  {
    key: 'skuter-yamaha-jog',
    title: 'Скутер Yamaha Jog',
    category: 'auto',
    basePrice: 28000,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Двухтактник, заводится на холодную', 'Вариатор обслужен, резина живая', 'Гараж освобождается, продаю'],
  },
  {
    key: 'pritsep-mzsa',
    title: 'Прицеп легковой МЗСА',
    category: 'auto',
    basePrice: 40000,
    jitter: 0.2,
    weight: 0.5,
    desc: ['Подвеска целая, дно без гнили', 'Тент новый, документы в порядке', 'Дача продана, прицеп без дела'],
  },
  {
    key: 'kvadrotsikl-detskiy',
    title: 'Квадроцикл детский 125 кубов',
    category: 'auto',
    basePrice: 35000,
    jitter: 0.22,
    weight: 0.5,
    desc: ['Заводится с кнопки, ездит бодро', 'Ограничитель скорости есть', 'Дети выросли, техника скучает'],
  },
  {
    key: 'motoblok-neva',
    title: 'Мотоблок Нева с фрезами',
    category: 'auto',
    basePrice: 25000,
    jitter: 0.22,
    weight: 0.7,
    desc: ['Мотор заводится хорошо, фрезы в комплекте', 'Был на двух сотках, справляется', 'Участок продали, техника лишняя'],
  },
  {
    key: 'shini-zimnie-r15',
    title: 'Шины зимние R15 (комплект)',
    category: 'auto',
    basePrice: 8000,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Протектор 6 мм, шипы на месте', 'Грыж и порезов нет', 'Смена машины, не подошли по диаметру'],
  },
  {
    key: 'avtomagnitola-android',
    title: 'Магнитола Android 9 дюймов',
    category: 'auto',
    basePrice: 6500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Навигация и Bluetooth работают', 'Камера заднего вида в комплекте', 'Продал машину, снял магнитолу'],
  },
  {
    key: 'bagazhnik-krysha',
    title: 'Багажник на крышу с замками',
    category: 'auto',
    basePrice: 5000,
    jitter: 0.28,
    desc: ['Дуги ровные, ключи в комплекте', 'Подходили на кроссовер, универсальные', 'Продаю, машина продана'],
  },
  {
    key: 'akb-60',
    title: 'Аккумулятор 60 Ач',
    category: 'auto',
    basePrice: 4500,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Крутит бодро, тест покажу', 'Корпус без трещин, клеммы чистые', 'Купил новый по гарантии, этот резервный'],
  },
  {
    key: 'signalizatsiya-starline',
    title: 'Сигнализация StarLine A93',
    category: 'auto',
    basePrice: 4500,
    jitter: 0.28,
    desc: ['Снят с машины, комплект полный', 'Брелоки оба работают, батарейки новые', 'Автозапуск настроен был, всё на месте'],
  },
  {
    key: 'generator-vaz',
    title: 'Генератор ВАЗ 2110',
    category: 'auto',
    basePrice: 3500,
    jitter: 0.3,
    desc: ['Рабочий, снял при замене на новый', 'Подшипники не гудят, диодный мост цел', 'Подойдёт на десятку и приору'],
  },
  {
    key: 'din-kolonki-para',
    title: 'Автодинамики 13 см, пара',
    category: 'auto',
    basePrice: 1800,
    jitter: 0.32,
    weight: 1.8,
    desc: ['Играют чисто, без хрипов', 'Магниты мощные, решётки есть', 'Менял всю акустику, эти остались'],
  },

  // ---------------- Детское ----------------
  {
    key: 'anex-kolyaska',
    title: 'Коляска Anex 2 в 1',
    category: 'kids',
    basePrice: 11500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Колёса целые, механизм складывания чёткий', 'Комплект: люлька и прогулка, дождевик', 'После одного ребёнка, всё помыто'],
  },
  {
    key: 'britax-kreslo',
    title: 'Автокресло Britax Römer',
    category: 'kids',
    basePrice: 5800,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Крепление изофикс, ремни целые', 'После аварий не было', 'Чехол постиран'],
  },
  {
    key: 'det-krovatka',
    title: 'Детская кроватка с матрасом',
    category: 'kids',
    basePrice: 3300,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Борта целые, планки надёжные', 'Матрас покупали недавно', 'Разбирается, перевозка простая'],
  },
  {
    key: 'vel-16',
    title: 'Велосипед детский 16"',
    category: 'kids',
    basePrice: 2800,
    jitter: 0.3,
    weight: 1.5,
    desc: ['На рост ребёнка 105-115', 'Помощные колёсики в комплекте', 'Цепь смазана, тормоз работает'],
  },
  {
    key: 'fisher-price',
    title: 'Развивающий центр Fisher-Price',
    category: 'kids',
    basePrice: 1700,
    jitter: 0.32,
    desc: ['Всё мигает и играет, батарейки свои', 'Пластик вымыт, ничего не отломано', 'Дочка выросла, отдаю дешевле'],
  },
  {
    key: 'lego-razves',
    title: 'Конструктор LEGO на развес (2 кг)',
    category: 'kids',
    basePrice: 2200,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Все детали целые, есть фигурки', 'Отмыты, отдам в пакете', 'Инструкции не сохранялись'],
  },
  {
    key: 'sanki-kanadka',
    title: 'Санки «Канадка»',
    category: 'kids',
    basePrice: 1100,
    jitter: 0.3,
    weight: 0.8,
    desc: ['Полозья ровные, спинка целая', 'Ремень безопасности на месте', 'Забирайте до снега, зима близко'],
  },

  {
    key: 'kolyaska-2v1',
    title: 'Коляска 2 в 1 универсальная',
    category: 'kids',
    basePrice: 12000,
    jitter: 0.22,
    weight: 0.8,
    desc: ['Люлька и прогулочный блок в комплекте', 'Колёса надувные, ход ровный', 'После одного малыша, всё вымыто'],
  },
  {
    key: 'vel-20',
    title: 'Велосипед детский 20 дюймов',
    category: 'kids',
    basePrice: 6000,
    jitter: 0.28,
    weight: 1.5,
    desc: ['На рост 120-135', 'Тормоза работают, цепь смазана', 'Покрашен аккуратно, без ржавчины'],
  },
  {
    key: 'det-elektromobil',
    title: 'Электромобиль детский джип',
    category: 'kids',
    basePrice: 6500,
    jitter: 0.25,
    weight: 1.5,
    desc: ['Ездит вперёд и назад, музыка играет', 'Батарея держит полчаса езды', 'Пульт родительский в комплекте'],
  },
  {
    key: 'batut-detskiy',
    title: 'Батут детский с сеткой',
    category: 'kids',
    basePrice: 7000,
    jitter: 0.25,
    weight: 0.8,
    desc: ['Диаметр 2 метра, сетка целая', 'Пружины все на месте', 'Разбирается, увезти несложно'],
  },
  {
    key: 'kolyaska-trost',
    title: 'Коляска-трость лёгкая',
    category: 'kids',
    basePrice: 4000,
    jitter: 0.28,
    weight: 1.5,
    desc: ['Складывается одной рукой', 'Колёса целые, тормоз работает', 'Для поездок и отпуска идеальна'],
  },
  {
    key: 'lego-technic',
    title: 'Конструктор LEGO Technic',
    category: 'kids',
    basePrice: 4500,
    jitter: 0.25,
    weight: 0.7,
    desc: ['Собран, инструкция и коробка есть', 'Все детали на месте, лишних нет', 'Собирается второй раз без проблем'],
  },
  {
    key: 'det-samokat',
    title: 'Самокат детский трёхколёсный',
    category: 'kids',
    basePrice: 2000,
    jitter: 0.3,
    weight: 1.8,
    desc: ['Колёса светятся при езде', 'Ручка регулируется по росту', 'Дека без трещин, катались сезон'],
  },
  {
    key: 'manezh-detskiy',
    title: 'Манеж детский складной',
    category: 'kids',
    basePrice: 3000,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Раскладывается за минуту', 'Сетка целая, дно чистое', 'Малыш подрос, манеж свободен'],
  },
  {
    key: 'stulchik-kormlenie',
    title: 'Стульчик для кормления',
    category: 'kids',
    basePrice: 2500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Столик снимается, ремни целые', 'Чехол вымыт, механизм надёжный', 'Готов к использованию, вымыт'],
  },
  {
    key: 'zheleznaya-doroga',
    title: 'Железная дорога с рельсами',
    category: 'kids',
    basePrice: 2000,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Паровозик едет, светит и сигналит', 'Рельсы все, соберётся круг', 'Коробка помята, комплект полный'],
  },
  {
    key: 'radionyanya',
    title: 'Радио-няня',
    category: 'kids',
    basePrice: 1500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Связь чёткая, батарейки держат долго', 'Два блока: родитель и малыш', 'Помогла первые два года'],
  },

  // ---------------- Книги ----------------
  {
    key: 'master-margarita',
    title: 'Булгаков «Мастер и Маргарита» (илл. изд.)',
    category: 'books',
    basePrice: 650,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Иллюстрированное издание, твёрдый переплёт', 'Страницы без подчёркиваний', 'Бережно хранилась'],
  },
  {
    key: 'hp-set',
    title: 'Гарри Поттер, все 7 томов (Росмэн)',
    category: 'books',
    basePrice: 3200,
    jitter: 0.25,
    desc: ['Все семь томов, издательство Росмэн', 'Обложки целые, корешки аккуратные', 'Продаю коллекцию целиком'],
  },
  {
    key: 'voina-i-mir',
    title: 'Толстой «Война и мир», 2 тома',
    category: 'books',
    basePrice: 380,
    jitter: 0.3,
    desc: ['Классическое издание, два тома', 'Блок цел, страницы чистые', 'Читал один раз'],
  },
  {
    key: 'fant-15',
    title: 'Фантастика, 15 книг (Стругацкие и др.)',
    category: 'books',
    basePrice: 850,
    jitter: 0.3,
    weight: 0.8,
    desc: ['Стругацкие, Лем, Саймак и другие', 'Издания девяностых, состояние разное', 'Отдам всё разом, по одной не продам'],
  },
  {
    key: 'enc-detskaya',
    title: 'Детская энциклопедия «Хочу всё знать»',
    category: 'books',
    basePrice: 450,
    jitter: 0.3,
    desc: ['Красочные иллюстрации, твёрдый переплёт', 'Ребёнок вырос, книга целая', 'Пять томов, все на месте'],
  },
  {
    key: 'biznes-5',
    title: 'Бизнес-литература, 5 книг',
    category: 'books',
    basePrice: 650,
    jitter: 0.3,
    desc: ['Кийосаки, Трейси и другие', 'Читаны один раз, без пометок', 'Отдам пачкой, пригодится начинающим'],
  },
  {
    key: 'marvel-12',
    title: 'Комиксы Marvel (12 выпусков)',
    category: 'books',
    basePrice: 800,
    jitter: 0.3,
    weight: 0.5,
    desc: ['Двенадцать выпусков, состояние хорошее', 'Без вырезанных страниц', 'Отдам коллекционеру дешевле'],
  },

  {
    key: 'dostoevsky-sobranie',
    title: 'Достоевский, собрание сочинений',
    category: 'books',
    basePrice: 3500,
    jitter: 0.3,
    weight: 0.7,
    desc: ['Двенадцать томов, состояние хорошее', 'Классическое издание, твёрдые обложки', 'Полка освобождается, отдаю комплектом'],
  },
  {
    key: 'knigi-sovetskie',
    title: 'Книги советские, стопка',
    category: 'books',
    basePrice: 800,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Классика и производственные романы', 'Кое-где дарственные надписи', 'Отдам всё сразу, на полке пылится'],
  },
  {
    key: 'detektivy-10',
    title: 'Детективы, 10 книг',
    category: 'books',
    basePrice: 700,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Донцова и компания, читать на пляж', 'Состояние читательское, страницы целые', 'Отдаю пачкой, дача будет рада'],
  },
  {
    key: 'klassika-shkolnaya',
    title: 'Школьная классика, 15 книг',
    category: 'books',
    basePrice: 900,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Программа с 5 по 11 класс', 'Пометок карандашом почти нет', 'Выпускной позади, книги свободны'],
  },
  {
    key: 'uchebniki-pachka',
    title: 'Учебники вуза, пачка',
    category: 'books',
    basePrice: 500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Матан, физика и программирование', 'Диплом получен, учебники свободны', 'Забирайте всё, вес приличный'],
  },
  {
    key: 'dune-roman',
    title: 'Роман «Дюна» Герберт',
    category: 'books',
    basePrice: 600,
    jitter: 0.3,
    desc: ['Издание хорошее, твёрдая обложка', 'Прочитан один раз, аккуратно', 'Фильм тоже хорош, но книга лучше'],
  },
  {
    key: 'manga-5',
    title: 'Манга, 5 томов',
    category: 'books',
    basePrice: 1500,
    jitter: 0.3,
    weight: 0.7,
    desc: ['Выпуски подряд, серия завершена', 'Обложки без заломов', 'Ушёл из увлечения, отдаю дешевле'],
  },
  {
    key: 'ezoterika-6',
    title: 'Эзотерика, 6 книг',
    category: 'books',
    basePrice: 600,
    jitter: 0.3,
    weight: 0.8,
    desc: ['Кастанеда и похожие авторы', 'Читаны, состояние нормальное', 'Этап пройден, книги ищут хозяина'],
  },
  {
    key: 'kulinariya-5',
    title: 'Кулинарные книги, 5 шт',
    category: 'books',
    basePrice: 500,
    jitter: 0.3,
    weight: 1.5,
    desc: ['Поваренная книга с картинками', 'Пятен нет, страницы целые', 'Готовим по интернету, книги простаивают'],
  },

  // ---------------- МУСОР: объявления «Отдам даром» ----------------
  {
    key: 'trash-stul',
    title: 'Стул сломанный, отдам даром',
    category: 'furniture',
    basePrice: 150,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Отдам даром, сломана ножка', 'Кто с руками — починит за вечер', 'Стоит у подъезда, самовывоз'],
  },
  {
    key: 'trash-monitor',
    title: 'Монитор битый, отдам даром',
    category: 'electronics',
    basePrice: 300,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Трещина на матрице, не включается', 'Отдам даром на запчасти', 'Заберите, пылится на балконе'],
  },
  {
    key: 'trash-velosiped',
    title: 'Велосипед ржавый без цепи, отдам даром',
    category: 'hobby',
    basePrice: 400,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Отдам даром, ржавый и без цепи', 'Колёса и рама целые, остальное под вопросом', 'Забирайте из гаража'],
  },
  {
    key: 'trash-mikrovolnovka',
    title: 'Микроволновка старая, не работает, отдам даром',
    category: 'appliances',
    basePrice: 200,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Не греет, отдам даром', 'Может пригодиться мастеру или на запчасти', 'Забирайте, места нет'],
  },
  {
    key: 'trash-divan',
    title: 'Диван порванный, отдам даром',
    category: 'furniture',
    basePrice: 450,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Обивка порвана, каркас крепкий', 'Отдам даром, помогу вынести', 'На дачу или на запчасти подойдёт'],
  },
  {
    key: 'trash-printer',
    title: 'Принтер старый, отдам даром',
    category: 'electronics',
    basePrice: 250,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Не печатает, отдам даром', 'Пусть будет донором', 'Забирайте до вечера, потом на мусорку'],
  },
  {
    key: 'trash-naushniki',
    title: 'Наушники без левого канала, отдам даром',
    category: 'electronics',
    basePrice: 150,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Левый канал умер, отдам даром', 'Провод целый, звук в правом есть', 'Забирайте смело, дефект честно пишу'],
  },
  {
    key: 'trash-rc-mashina',
    title: 'Машина на радиоуправлении не едет, отдам даром',
    category: 'hobby',
    basePrice: 200,
    jitter: 0.4,
    weight: 0.8,
    desc: ['Не едет, отдам даром', 'Мотор возможно живой, пульт в комплекте', 'Кому на запчасти или ребёнку на корпус'],
  },
]
