// Фото конкретных товаров (сгенерированы в public/img/p/).
// Если для itemKey есть фото — оно перекрывает картинку категории.
import { CATEGORY_IMAGE } from '@/lib/catalog-types'

const PRODUCT_IMAGES: Record<string, string> = {
  'iphone-12': '/img/p/iphone-12.jpg',
  'iphone-11': '/img/p/iphone-11.jpg',
  'iphone-13': '/img/p/iphone-13.jpg',
  'iphone-xr': '/img/p/iphone-xr.jpg',
  'redmi-note-12': '/img/p/redmi-note-12.jpg',
  'galaxy-s22': '/img/p/galaxy-s22.jpg',
  'galaxy-a54': '/img/p/galaxy-a54.jpg',
  'galaxy-s21': '/img/p/galaxy-s21.jpg',
  'poco-x5-pro': '/img/p/poco-x5-pro.jpg',
  'ps5': '/img/p/ps5.jpg',
  'ps4-slim': '/img/p/ps4-slim.jpg',
  'nintendo-switch': '/img/p/nintendo-switch.jpg',
  'airpods-pro-2': '/img/p/airpods-pro-2.jpg',
  'apple-watch-7': '/img/p/apple-watch-7.jpg',
  'yandex-station-mini': '/img/p/yandex-station-mini.jpg',
  'macbook-air-2020': '/img/p/macbook-air-2020.jpg',
  'pc-i5-build': '/img/p/pc-i5-build.jpg',
  'pc-r5-build': '/img/p/pc-r5-build.jpg',
  'thinkpad-t480': '/img/p/thinkpad-t480.jpg',
  'lenovo-ideapad-3': '/img/p/lenovo-ideapad-3.jpg',
  'acer-nitro-5': '/img/p/acer-nitro-5.jpg',
  'asus-tuf-f15': '/img/p/asus-tuf-f15.jpg',
  'hp-pavilion-15': '/img/p/hp-pavilion-15.jpg',
  'asus-vivobook-15': '/img/p/asus-vivobook-15.jpg',
  'levis-501': '/img/p/levis-501.jpg',
  'zara-hoodie': '/img/p/zara-hoodie.jpg',
  'puhovik-uniqlo': '/img/p/puhovik-uniqlo.jpg',
  'mango-dress': '/img/p/mango-dress.jpg',
  'tommy-tishka': '/img/p/tommy-tishka.jpg',
  'adidas-sportcost': '/img/p/adidas-sportcost.jpg',
  'nike-af1': '/img/p/nike-af1.jpg',
  'adidas-samba': '/img/p/adidas-samba.jpg',
  'nb-574': '/img/p/nb-574.jpg',
  'aj1-mid': '/img/p/aj1-mid.jpg',
  'asics-kayano-14': '/img/p/asics-kayano-14.jpg',
  'vans-old-skool': '/img/p/vans-old-skool.jpg',
  'robot-xiaomi': '/img/p/robot-xiaomi.jpg',
  'lg-stiralka': '/img/p/lg-stiralka.jpg',
  'svch-samsung': '/img/p/svch-samsung.jpg',
  'multivarka-redmond': '/img/p/multivarka-redmond.jpg',
  'tv-samsung-43': '/img/p/tv-samsung-43.jpg',
  'monitor-lg-24': '/img/p/monitor-lg-24.jpg',
  'divan-knizhka': '/img/p/divan-knizhka.jpg',
  'friheten': '/img/p/friheten.jpg',
  'komp-stol': '/img/p/komp-stol.jpg',
  'billy': '/img/p/billy.jpg',
  'ganteli-16': '/img/p/ganteli-16.jpg',
  'xiaomi-m365': '/img/p/xiaomi-m365.jpg',
  'advocam': '/img/p/advocam.jpg',
  'anex-kolyaska': '/img/p/anex-kolyaska.jpg',
  'aquarium-60': '/img/p/aquarium-60.jpg',
  'at-lp60x': '/img/p/at-lp60x.jpg',
  'atlant-holodilnik': '/img/p/atlant-holodilnik.jpg',
  'avtokompressor': '/img/p/avtokompressor.jpg',
  'bauer-konki': '/img/p/bauer-konki.jpg',
  'bean-bag': '/img/p/bean-bag.jpg',
  'begovaya-dorozhka': '/img/p/begovaya-dorozhka.jpg',
  'biznes-5': '/img/p/biznes-5.jpg',
  'bosch-duhovka': '/img/p/bosch-duhovka.jpg',
  'britax-kreslo': '/img/p/britax-kreslo.jpg',
  'burton-custom': '/img/p/burton-custom.jpg',
  'carhartt-detroit': '/img/p/carhartt-detroit.jpg',
  'dell-latitude-7490': '/img/p/dell-latitude-7490.jpg',
  'delonghi-kofemashina': '/img/p/delonghi-kofemashina.jpg',
  'det-krovatka': '/img/p/det-krovatka.jpg',
  'diski-r16': '/img/p/diski-r16.jpg',
  'domkrat-2t': '/img/p/domkrat-2t.jpg',
  'dualshock-4': '/img/p/dualshock-4.jpg',
  'dyson-v8': '/img/p/dyson-v8.jpg',
  'eames-kreslo': '/img/p/eames-kreslo.jpg',
  'enc-detskaya': '/img/p/enc-detskaya.jpg',
  'fant-15': '/img/p/fant-15.jpg',
  'fender-champion-20': '/img/p/fender-champion-20.jpg',
  'fender-strat-mex': '/img/p/fender-strat-mex.jpg',
  'fisher-price': '/img/p/fisher-price.jpg',
  'galaxy-watch-4': '/img/p/galaxy-watch-4.jpg',
  'garmin-etrex': '/img/p/garmin-etrex.jpg',
  'henderson-kostyum': '/img/p/henderson-kostyum.jpg',
  'hjc-shlem': '/img/p/hjc-shlem.jpg',
  'hp-set': '/img/p/hp-set.jpg',
  'huawei-matebook-d15': '/img/p/huawei-matebook-d15.jpg',
  'huawei-p30-pro': '/img/p/huawei-p30-pro.jpg',
  'iphone-se-2020': '/img/p/iphone-se-2020.jpg',
  'karkasson': '/img/p/karkasson.jpg',
  'keychron-k2': '/img/p/keychron-k2.jpg',
  'komod-sosna': '/img/p/komod-sosna.jpg',
  'krovat-160': '/img/p/krovat-160.jpg',
  'lego-razves': '/img/p/lego-razves.jpg',
  'macbook-air-2017': '/img/p/macbook-air-2017.jpg',
  'macbook-pro-2015': '/img/p/macbook-pro-2015.jpg',
  'marvel-12': '/img/p/marvel-12.jpg',
  'massimo-palto': '/img/p/massimo-palto.jpg',
  'master-margarita': '/img/p/master-margarita.jpg',
  'metalloiskatel-xterra': '/img/p/metalloiskatel-xterra.jpg',
  'msi-gf63': '/img/p/msi-gf63.jpg',
  'noirot-konvektor': '/img/p/noirot-konvektor.jpg',
  'nokian-8': '/img/p/nokian-8.jpg',
  'palatka-3': '/img/p/palatka-3.jpg',
  'pioneer-2din': '/img/p/pioneer-2din.jpg',
  'pixel-6a': '/img/p/pixel-6a.jpg',
  'polushubok': '/img/p/polushubok.jpg',
  'poperechniny': '/img/p/poperechniny.jpg',
  'puma-suede': '/img/p/puma-suede.jpg',
  'realme-gt-neo-3': '/img/p/realme-gt-neo-3.jpg',
  'reebok-classic': '/img/p/reebok-classic.jpg',
  'rollerblade': '/img/p/rollerblade.jpg',
  'sanki-kanadka': '/img/p/sanki-kanadka.jpg',
  'shkaf-kupe': '/img/p/shkaf-kupe.jpg',
  'shtanga-50': '/img/p/shtanga-50.jpg',
  'sony-wh-1000xm4': '/img/p/sony-wh-1000xm4.jpg',
  'squier-strat': '/img/p/squier-strat.jpg',
  'stels-navigator': '/img/p/stels-navigator.jpg',
  'teleskop-skywatcher': '/img/p/teleskop-skywatcher.jpg',
  'thinkpad-x1': '/img/p/thinkpad-x1.jpg',
  'tnf-kurtka': '/img/p/tnf-kurtka.jpg',
  'trash-divan': '/img/p/trash-divan.jpg',
  'trash-mikrovolnovka': '/img/p/trash-mikrovolnovka.jpg',
  'trash-monitor': '/img/p/trash-monitor.jpg',
  'trash-naushniki': '/img/p/trash-naushniki.jpg',
  'trash-printer': '/img/p/trash-printer.jpg',
  'trash-rc-mashina': '/img/p/trash-rc-mashina.jpg',
  'trash-stul': '/img/p/trash-stul.jpg',
  'trash-velosiped': '/img/p/trash-velosiped.jpg',
  'turnik': '/img/p/turnik.jpg',
  'ukulele': '/img/p/ukulele.jpg',
  'vel-16': '/img/p/vel-16.jpg',
  'velotrenazher': '/img/p/velotrenazher.jpg',
  'vinil-20': '/img/p/vinil-20.jpg',
  'voina-i-mir': '/img/p/voina-i-mir.jpg',
  'wilson-raketki': '/img/p/wilson-raketki.jpg',
  'xbox-series-s': '/img/p/xbox-series-s.jpg',
  'yamaha-f310': '/img/p/yamaha-f310.jpg',
  'yamaha-psr-e373': '/img/p/yamaha-psr-e373.jpg',
}

/** Фото для itemKey: продукт-фото, иначе фото категории. */
export function itemImage(itemKey?: string | null, category?: string | null): string {
  if (itemKey && PRODUCT_IMAGES[itemKey]) return PRODUCT_IMAGES[itemKey]
  if (category && CATEGORY_IMAGE[category]) return CATEGORY_IMAGE[category]
  return '/img/cat-electronics.jpg'
}

/** Есть ли у товара собственное фото. */
export function hasProductImage(itemKey: string): boolean {
  return itemKey in PRODUCT_IMAGES
}
